// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GlobalSearchResult = { "type": "task", id: string, task_number: string, title: string, status: string, } | { "type": "client", id: string, name: string, email: string | null, } | { "type": "material", id: string, name: string, sku: string, } | { "type": "quote", id: string, quote_number: string, description: string | null, };
