// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

// Auth types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAccount = { id: string, email: string, username: string, first_name: string, last_name: string, role: UserRole, password_hash: string, salt: string | null, phone: string | null, is_active: boolean, last_login: bigint | null, login_count: number, preferences: string | null, synced: boolean, last_synced_at: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserRole = "admin" | "technician" | "supervisor" | "viewer";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A simplified session stored as a UUID in SQLite (no JWT, no 2FA).
 */
export type UserSession = { id: string, user_id: string, username: string, email: string, role: UserRole, token: string, expires_at: string, last_activity: string, created_at: string, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateUserRequest = { email: string, first_name: string, last_name: string, role: string, password: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateUserRequest = { email: string | null, first_name: string | null, last_name: string | null, role: string | null, is_active: boolean | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAction = { "action": "Create", data: CreateUserRequest, } | { "action": "Get", id: string, } | { "action": "Update", id: string, data: UpdateUserRequest, } | { "action": "Delete", id: string, } | { "action": "List", limit: number | null, offset: number | null, } | { "action": "ChangePassword", id: string, new_password: string, } | { "action": "ChangeRole", id: string, new_role: UserRole, } | { "action": "Ban", id: string, } | { "action": "Unban", id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserListResponse = { data: Array<UserAccount>, };
