// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

import type { Task, TaskPriority, TaskStatus } from './tasks';

// Event types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventType = "meeting" | "appointment" | "task" | "reminder" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventParticipant = { id: string, name: string, email: string | null, status: ParticipantStatus, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParticipantStatus = "accepted" | "declined" | "tentative" | "needsaction";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventStatus = "confirmed" | "tentative" | "cancelled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateEventInput = { title: string, description: string | null, startDatetime: string, endDatetime: string, allDay: boolean | null, timezone: string | null, eventType: EventType | null, category: string | null, taskId: string | null, clientId: string | null, technicianId: string | null, location: string | null, meetingLink: string | null, isVirtual: boolean | null, participants: Array<EventParticipant> | null, reminders: Array<number> | null, color: string | null, tags: Array<string> | null, notes: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateEventInput = { title: string | null, description: string | null, startDatetime: string | null, endDatetime: string | null, allDay: boolean | null, timezone: string | null, eventType: EventType | null, category: string | null, taskId: string | null, clientId: string | null, location: string | null, meetingLink: string | null, isVirtual: boolean | null, participants: Array<EventParticipant> | null, status: EventStatus | null, reminders: Array<number> | null, color: string | null, tags: Array<string> | null, notes: string | null, };



// Calendar additional types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarEvent = { id: string, title: string, description: string | null, startDatetime: string, endDatetime: string, allDay: boolean, timezone: string, eventType: EventType, category: string | null, taskId: string | null, clientId: string | null, technicianId: string | null, location: string | null, meetingLink: string | null, isVirtual: boolean, participants: Array<EventParticipant>, isRecurring: boolean, recurrenceRule: string | null, parentEventId: string | null, reminders: Array<number>, status: EventStatus, color: string | null, tags: Array<string>, notes: string | null, synced: boolean, lastSyncedAt: bigint | null, createdAt: bigint, updatedAt: bigint, createdBy: string | null, updatedBy: string | null, deletedAt: bigint | null, deletedBy: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CalendarTask represents a task with calendar-specific information
 * Maps to the calendar_tasks SQL View
 */
export type CalendarTask = { id: string, task_number: string, title: string, status: CalendarTaskStatus, priority: CalendarTaskPriority, scheduled_date: string, start_time: string | null, end_time: string | null, vehicle_plate: string | null, vehicle_model: string | null, technician_id: string | null, technician_name: string | null, client_id: string | null, client_name: string | null, estimated_duration: number | null, actual_duration: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task status values mirrored for calendar display.
 *
 * These variants must remain in sync with `tasks::domain::models::task::TaskStatus`.
 * A calendar view should not depend on the tasks bounded context directly.
 */
export type CalendarTaskStatus = "draft" | "scheduled" | "in_progress" | "completed" | "cancelled" | "on_hold" | "pending" | "invalid" | "archived" | "failed" | "overdue" | "assigned" | "paused";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task priority values mirrored for calendar display.
 *
 * These variants must remain in sync with `tasks::domain::models::task::TaskPriority`.
 */
export type CalendarTaskPriority = "low" | "medium" | "high" | "urgent";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calendar filter for tasks
 */
export type CalendarFilter = { date_range: CalendarDateRange, technician_ids: Array<string> | null, statuses: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conflict detection result
 */
export type ConflictDetection = { has_conflict: boolean, conflict_type: string | null, conflicting_tasks: Array<CalendarTask>, message: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Date range filter for calendar queries
 */
export type CalendarDateRange = { start_date: string, end_date: string, };
