// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

import type { PaginationInfo, SortOrder, Task } from './tasks';

// Client types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main Client entity
 */
export type Client = { id: string, name: string, email: string | null, phone: string | null, customer_type: CustomerType, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, total_tasks: number, active_tasks: number, completed_tasks: number, last_task_date: string | null, created_at: string, updated_at: string, created_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client with associated tasks
 */
export type ClientWithTasks = { id: string, name: string, email: string | null, phone: string | null, customer_type: CustomerType, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, total_tasks: number, active_tasks: number, completed_tasks: number, last_task_date: string | null, created_at: string, updated_at: string, created_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, tasks: Array<Task> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversion implementations for database operations
 * Client query parameters for listing and filtering
 */
export type ClientQuery = { page: number | null, limit: number | null, search: string | null, customer_type: CustomerType | null, sort_by: string | null, sort_order: SortOrder | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Customer type enumeration
 */
export type CustomerType = "individual" | "business";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create client request
 */
export type CreateClientRequest = { name: string, email: string | null, phone: string | null, customer_type: CustomerType, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update client request
 */
export type UpdateClientRequest = { id: string, name: string | null, email: string | null, phone: string | null, customer_type: CustomerType | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client list response with pagination
 */
export type ClientListResponse = { data: Array<Client>, pagination: PaginationInfo, statistics: ClientStatistics | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client statistics
 */
export type ClientStatistics = { total_clients: bigint, individual_clients: bigint, business_clients: bigint, clients_with_tasks: bigint, new_clients_this_month: bigint, };
