// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

import type { PaginationInfo } from './tasks';

// Auto-generated TypeScript types from Rust backend
// Do not edit manually - generated by export-types.rs

// JSON value helpers (mirrors Rust serde_json::Value)
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonObject | JsonArray;
export type JsonObject = { [key: string]: JsonValue };
export type JsonArray = JsonValue[];

// Error types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Standard API error envelope returned to the frontend.
 */
export type ApiError = { message: string, code: string, details: JsonValue | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compressed API envelope for large payloads.
 */
export type CompressedApiResponse = { success: boolean, message: string | null, error_code: string | null, compressed: boolean, data: string | null, error: ApiError | null, correlation_id: string | null, };


// Repository types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paginated result
 */
export type PaginatedResult<T> = { data: Array<T>, pagination: PaginationInfo, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cache statistics
 */
export type CacheStats = { size: number, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GPS coordinates
 */
export type GpsLocation = { latitude: number, longitude: number, accuracy: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Film type for PPF
 */
export type FilmType = "standard" | "premium" | "matte" | "colored";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Weather conditions for intervention
 */
export type WeatherCondition = "sunny" | "cloudy" | "rainy" | "foggy" | "windy" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lighting conditions
 */
export type LightingCondition = "natural" | "artificial" | "mixed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Work location type
 */
export type WorkLocation = "indoor" | "outdoor" | "semi_covered";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wrapper type for timestamps that serializes to ISO string
 */
export type TimestampString = bigint | null;
