// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

import type { JsonValue } from './common';

// Photo types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Photo = { id: string, intervention_id: string, step_id: string | null, step_number: number | null, file_path: string, file_name: string | null, file_size: bigint | null, mime_type: string, width: number | null, height: number | null, photo_type: PhotoType | null, photo_category: PhotoCategory | null, photo_angle: string | null, zone: string | null, title: string | null, description: string | null, notes: string | null, annotations: JsonValue | null, gps_location_lat: number | null, gps_location_lon: number | null, gps_location_accuracy: number | null, quality_score: number | null, blur_score: number | null, exposure_score: number | null, composition_score: number | null, is_required: boolean, is_approved: boolean, approved_by: string | null, approved_at: bigint | null, rejection_reason: string | null, synced: boolean, storage_url: string | null, upload_retry_count: number, upload_error: string | null, last_synced_at: bigint | null, captured_at: bigint | null, uploaded_at: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhotoType = "before" | "during" | "after";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhotoCategory = "vehicle_condition" | "workspace" | "step_progress" | "qc_check" | "final_result" | "other";
