// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

import type { FilmType, JsonValue, LightingCondition, TimestampString, WeatherCondition, WorkLocation } from './common';
import type { Photo } from './documents';

// Intervention types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main intervention struct
 */
export type Intervention = { id: string, task_id: string, task_number: string | null, status: InterventionStatus, vehicle_plate: string, vehicle_model: string | null, vehicle_make: string | null, vehicle_year: number | null, vehicle_color: string | null, vehicle_vin: string | null, client_id: string | null, client_name: string | null, client_email: string | null, client_phone: string | null, technician_id: string | null, technician_name: string | null, intervention_type: InterventionType, 
/**
 * Number of completed steps (0-based count, not array index)
 */
current_step: number, completion_percentage: number, ppf_zones_config: Array<string> | null, ppf_zones_extended: JsonValue | null, film_type: FilmType | null, film_brand: string | null, film_model: string | null, scheduled_at: TimestampString, started_at: TimestampString, completed_at: TimestampString, paused_at: TimestampString, estimated_duration: number | null, actual_duration: number | null, weather_condition: WeatherCondition | null, lighting_condition: LightingCondition | null, work_location: WorkLocation | null, temperature_celsius: number | null, humidity_percentage: number | null, start_location_lat: number | null, start_location_lon: number | null, start_location_accuracy: number | null, end_location_lat: number | null, end_location_lon: number | null, end_location_accuracy: number | null, customer_satisfaction: number | null, quality_score: number | null, final_observations: Array<string> | null, customer_signature: string | null, customer_comments: string | null, metadata: JsonValue | null, notes: string | null, special_instructions: string | null, device_info: JsonValue | null, app_version: string | null, synced: boolean, last_synced_at: bigint | null, sync_error: string | null, created_at: bigint, updated_at: bigint, created_by: string | null, updated_by: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention status enum
 */
export type InterventionStatus = "pending" | "in_progress" | "paused" | "completed" | "cancelled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention type
 */
export type InterventionType = "ppf" | "ceramic" | "detailing" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter for intervention queries
 */
export type InterventionFilter = { task_id: string | null, status: string | null, technician_id: string | null, client_id: string | null, priority: string | null, from_date: string | null, to_date: string | null, intervention_type: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for bulk updating interventions
 */
export type BulkUpdateInterventionRequest = { intervention_ids: Array<string>, status: string | null, technician_id: string | null, priority: string | null, updates: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GPS coordinates for location tracking
 */
export type GpsCoordinates = { latitude: number, longitude: number, accuracy: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention step struct
 */
export type InterventionStep = { id: string, intervention_id: string, step_number: number, step_name: string, step_type: StepType, step_status: StepStatus, description: string | null, instructions: JsonValue | null, quality_checkpoints: Array<string> | null, is_mandatory: boolean, requires_photos: boolean, min_photos_required: number, max_photos_allowed: number, started_at: TimestampString, completed_at: TimestampString, paused_at: TimestampString, duration_seconds: number | null, estimated_duration_seconds: number | null, step_data: JsonValue | null, collected_data: JsonValue | null, measurements: JsonValue | null, observations: Array<string> | null, photo_count: number, required_photos_completed: boolean, photo_urls: Array<string> | null, validation_data: JsonValue | null, validation_errors: Array<string> | null, validation_score: number | null, requires_supervisor_approval: boolean, approved_by: string | null, approved_at: TimestampString, rejection_reason: string | null, location_lat: number | null, location_lon: number | null, location_accuracy: number | null, device_timestamp: TimestampString, server_timestamp: TimestampString, title: string | null, notes: string | null, synced: boolean, last_synced_at: TimestampString, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step type enum
 */
export type StepType = "inspection" | "preparation" | "installation" | "finalization";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to start a new intervention
 */
export type StartInterventionRequest = { task_id: string, intervention_number: string | null, ppf_zones: Array<string>, custom_zones: Array<string> | null, film_type: string, film_brand: string | null, film_model: string | null, weather_condition: string, lighting_condition: string, work_location: string, temperature: number | null, humidity: number | null, technician_id: string, assistant_ids: Array<string> | null, scheduled_start: string, estimated_duration: number, gps_coordinates: GpsCoordinates | null, address: string | null, notes: string | null, customer_requirements: Array<string> | null, special_instructions: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to advance a step
 */
export type AdvanceStepRequest = { intervention_id: string, step_id: string, collected_data: JsonValue, photos: Array<string> | null, notes: string | null, quality_check_passed: boolean, issues: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for saving step progress without advancing
 */
export type SaveStepProgressRequest = { step_id: string, collected_data: JsonValue, notes: string | null, photos: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to finalize an intervention
 */
export type FinalizeInterventionRequest = { intervention_id: string, collected_data: JsonValue | null, photos: Array<string> | null, customer_satisfaction: number | null, quality_score: number | null, final_observations: Array<string> | null, customer_signature: string | null, customer_comments: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for starting an intervention
 */
export type StartInterventionResponse = { intervention: Intervention, steps: Array<InterventionStep>, initial_requirements: Array<StepRequirement>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for advancing a step
 */
export type AdvanceStepResponse = { step: InterventionStep, next_step: InterventionStep | null, progress_percentage: number, requirements_completed: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for saving step progress
 */
export type SaveStepProgressResponse = { step: InterventionStep, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for finalizing an intervention
 */
export type FinalizeInterventionResponse = { intervention: Intervention, metrics: InterventionMetrics, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step requirement for workflow validation
 */
export type StepRequirement = { step_id: string, requirement_type: string, description: string, is_mandatory: boolean, is_completed: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention step with associated photos
 */
export type InterventionStepWithPhotos = { step: InterventionStep, photos: Array<Photo>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention with all related data
 */
export type InterventionWithDetails = { intervention: Intervention, steps: Array<InterventionStepWithPhotos>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress tracking for interventions
 */
export type InterventionProgress = { intervention_id: string, current_step: number, total_steps: number, completed_steps: number, completion_percentage: number, estimated_time_remaining: number | null, status: InterventionStatus, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention metrics for finalization
 */
export type InterventionMetrics = { total_duration_minutes: number, completion_rate: number, quality_score: number | null, customer_satisfaction: number | null, steps_completed: number, total_steps: number, photos_taken: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step status enum
 */
export type StepStatus = "pending" | "in_progress" | "paused" | "completed" | "failed" | "skipped" | "rework";
