// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

import type { JsonValue } from './common';

// Material types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material types for PPF workflows
 */
export type MaterialType = "ppf_film" | "adhesive" | "cleaning_solution" | "tool" | "consumable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unit of measure for materials
 */
export type UnitOfMeasure = "piece" | "meter" | "liter" | "gram" | "roll";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material inventory item
 */
export type Material = { id: string, sku: string, name: string, description: string | null, material_type: MaterialType, category: string | null, subcategory: string | null, category_id: string | null, brand: string | null, model: string | null, specifications: JsonValue | null, unit_of_measure: UnitOfMeasure, current_stock: number, minimum_stock: number | null, maximum_stock: number | null, reorder_point: number | null, unit_cost: number | null, currency: string, supplier_id: string | null, supplier_name: string | null, supplier_sku: string | null, quality_grade: string | null, certification: string | null, expiry_date: string | null, batch_number: string | null, serial_numbers: Array<string> | null, is_active: boolean, is_discontinued: boolean, storage_location: string | null, warehouse_id: string | null, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TypeScript-compatible Material with i64 timestamps
 */
export type MaterialTS = { id: string, sku: string, name: string, description: string | null, material_type: MaterialType, category: string | null, subcategory: string | null, category_id: string | null, brand: string | null, model: string | null, specifications: string | null, unit_of_measure: UnitOfMeasure, current_stock: number, minimum_stock: number | null, maximum_stock: number | null, reorder_point: number | null, unit_cost: number | null, currency: string, supplier_id: string | null, supplier_name: string | null, supplier_sku: string | null, quality_grade: string | null, certification: string | null, expiry_date: bigint | null, batch_number: string | null, serial_numbers: Array<string> | null, is_active: boolean, is_discontinued: boolean, storage_location: string | null, warehouse_id: string | null, created_at: bigint, updated_at: bigint, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: bigint | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material consumption record for interventions
 */
export type MaterialConsumption = { id: string, intervention_id: string, material_id: string, step_id: string | null, quantity_used: number, unit_cost: number | null, total_cost: number | null, waste_quantity: number, waste_reason: string | null, batch_used: string | null, expiry_used: string | null, quality_notes: string | null, step_number: number | null, recorded_by: string | null, recorded_at: string, created_at: string, updated_at: string, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TypeScript-compatible MaterialConsumption
 */
export type MaterialConsumptionTS = { id: string, intervention_id: string, material_id: string, step_id: string | null, quantity_used: number, unit_cost: number | null, total_cost: number | null, waste_quantity: number, waste_reason: string | null, batch_used: string | null, expiry_used: bigint | null, quality_notes: string | null, step_number: number | null, recorded_by: string | null, recorded_at: bigint, created_at: bigint, updated_at: bigint, synced: boolean, last_synced_at: bigint | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material inventory statistics
 */
export type MaterialStats = { total_materials: number, active_materials: number, low_stock_materials: number, expired_materials: number, total_value: number, materials_by_type: { [key in string]?: number }, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enhanced inventory statistics
 */
export type InventoryStats = { total_materials: number, active_materials: number, low_stock_materials: number, expired_materials: number, total_value: number, materials_by_category: { [key in string]?: number }, recent_transactions: Array<InventoryTransaction>, stock_turnover_rate: number, average_inventory_age: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inventory transaction record
 */
export type InventoryTransaction = { id: string, material_id: string, transaction_type: InventoryTransactionType, quantity: number, previous_stock: number, new_stock: number, reference_number: string | null, reference_type: string | null, notes: string | null, unit_cost: number | null, total_cost: number | null, warehouse_id: string | null, location_from: string | null, location_to: string | null, batch_number: string | null, expiry_date: string | null, quality_status: string | null, intervention_id: string | null, step_id: string | null, performed_by: string, performed_at: string, created_at: string, updated_at: string, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TypeScript-compatible InventoryTransaction
 */
export type InventoryTransactionTS = { id: string, material_id: string, transaction_type: string, quantity: number, previous_stock: number, new_stock: number, reference_number: string | null, reference_type: string | null, notes: string | null, unit_cost: number | null, total_cost: number | null, warehouse_id: string | null, location_from: string | null, location_to: string | null, batch_number: string | null, expiry_date: bigint | null, quality_status: string | null, intervention_id: string | null, step_id: string | null, performed_by: string, performed_at: bigint, created_at: bigint, updated_at: bigint, synced: boolean, last_synced_at: bigint | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transaction types for inventory movements
 */
export type InventoryTransactionType = "stock_in" | "stock_out" | "adjustment" | "transfer" | "waste" | "return";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supplier information
 */
export type Supplier = { id: string, name: string, code: string | null, contact_person: string | null, email: string | null, phone: string | null, website: string | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, business_license: string | null, payment_terms: string | null, lead_time_days: number, is_active: boolean, is_preferred: boolean, quality_rating: number | null, delivery_rating: number | null, on_time_delivery_rate: number | null, notes: string | null, special_instructions: string | null, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material category for hierarchical organization
 */
export type MaterialCategory = { id: string, name: string, code: string | null, parent_id: string | null, level: number, description: string | null, color: string | null, is_active: boolean, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material consumption summary for an intervention
 */
export type InterventionMaterialSummary = { intervention_id: string, total_materials_used: number, total_cost: number, materials: Array<MaterialConsumptionSummary>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of material consumption
 */
export type MaterialConsumptionSummary = { material_id: string, material_name: string, material_type: string, quantity_used: number, unit_cost: number | null, total_cost: number | null, waste_quantity: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inventory movement summary
 */
export type InventoryMovementSummary = { material_id: string, material_name: string, total_stock_in: number, total_stock_out: number, net_movement: number, current_stock: number, last_transaction_date: string | null, };
