// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Notification = { id: string, created_at: string, type: string, title: string, message: string, entity_type: string, entity_id: string, entity_url: string, read: boolean, user_id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationChannel = "Email" | "Sms" | "Push";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationType = "TaskAssignment" | "TaskUpdate" | "TaskCompletion" | "StatusChange" | "OverdueWarning" | "SystemAlert" | "NewAssignment" | "DeadlineReminder" | "QualityApproval";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationTemplate = { id: string, name: string, notification_type: NotificationType, channel: NotificationChannel, subject_template: string, body_template: string, variables: Array<string>, is_active: boolean, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationMessage = { id: string, user_id: string, notification_type: NotificationType, channel: NotificationChannel, recipient: string, subject: string | null, body: string, priority: NotificationPriority, status: NotificationStatus, scheduled_at: string, sent_at: string, error_message: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationPriority = "Low" | "Normal" | "High" | "Critical";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationStatus = "Pending" | "Sent" | "Failed" | "Cancelled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TemplateVariables = { user_name: string | null, task_title: string | null, task_id: string | null, client_name: string | null, due_date: string | null, status: string | null, priority: string | null, assignee_name: string | null, system_message: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmailProvider = "SendGrid" | "Mailgun" | "Smtp";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmailConfig = { provider: EmailProvider, api_key: string, from_email: string, from_name: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmsProvider = "Twilio" | "AwsSns";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmsConfig = { provider: SmsProvider, api_key: string, from_number: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationConfig = { email: EmailConfig | null, sms: SmsConfig | null, push_enabled: boolean, quiet_hours_start: string | null, quiet_hours_end: string | null, timezone: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateNotificationConfigRequest = { email_provider: string | null, email_api_key: string | null, email_from_email: string | null, email_from_name: string | null, sms_provider: string | null, sms_api_key: string | null, sms_from_number: string | null, push_enabled: boolean | null, quiet_hours_start: string | null, quiet_hours_end: string | null, timezone: string | null, correlation_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SendNotificationRequest = { user_id: string, notification_type: NotificationType, recipient: string, variables: TemplateVariables, correlation_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message entity representing a single message
 */
export type Message = { id: string, message_type: string, sender_id: string | null, recipient_id: string | null, recipient_email: string | null, recipient_phone: string | null, subject: string | null, body: string, template_id: string | null, task_id: string | null, client_id: string | null, status: string, priority: string, scheduled_at: bigint | null, sent_at: bigint | null, read_at: bigint | null, error_message: string | null, metadata: string | null, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message types supported by the system
 */
export type MessageType = "Email" | "Sms" | "InApp";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message status enumeration
 */
export type MessageStatus = "Pending" | "Sent" | "Delivered" | "Failed" | "Read";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message priority levels
 */
export type MessagePriority = "Low" | "Normal" | "High" | "Urgent";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message query filters
 */
export type MessageQuery = { message_type: string | null, sender_id: string | null, recipient_id: string | null, task_id: string | null, client_id: string | null, status: string | null, priority: string | null, date_from: bigint | null, date_to: bigint | null, limit: number | null, offset: number | null, correlation_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message list response
 */
export type MessageListResponse = { messages: Array<Message>, total: number, has_more: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message template for reusable messages
 */
export type MessageTemplate = { id: string, name: string, description: string | null, message_type: string, subject: string | null, body: string, variables: string | null, category: string, is_active: boolean, created_by: string | null, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create/update a message template
 */
export type MessageTemplateRequest = { name: string, description: string | null, message_type: string, subject: string | null, body: string, variables: Array<string> | null, category: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to send a new message
 */
export type SendMessageRequest = { message_type: string, recipient_id: string | null, recipient_email: string | null, recipient_phone: string | null, subject: string | null, body: string, template_id: string | null, task_id: string | null, client_id: string | null, priority: string | null, scheduled_at: bigint | null, correlation_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User notification preferences
 */
export type NotificationPreferences = { id: string, user_id: string, email_enabled: boolean, sms_enabled: boolean, in_app_enabled: boolean, task_assigned: boolean, task_updated: boolean, task_completed: boolean, task_overdue: boolean, client_created: boolean, client_updated: boolean, system_alerts: boolean, maintenance_notifications: boolean, quiet_hours_enabled: boolean, quiet_hours_start: string | null, quiet_hours_end: string | null, email_frequency: string, email_digest_time: string, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update notification preferences
 */
export type UpdateNotificationPreferencesRequest = { email_enabled: boolean | null, sms_enabled: boolean | null, in_app_enabled: boolean | null, task_assigned: boolean | null, task_updated: boolean | null, task_completed: boolean | null, task_overdue: boolean | null, client_created: boolean | null, client_updated: boolean | null, system_alerts: boolean | null, maintenance_notifications: boolean | null, quiet_hours_enabled: boolean | null, quiet_hours_start: string | null, quiet_hours_end: string | null, email_frequency: string | null, email_digest_time: string | null, correlation_id: string | null, };
