// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

// Organization types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Organization = { id: string, name: string, slug: string | null, legal_name: string | null, tax_id: string | null, siret: string | null, registration_number: string | null, email: string | null, phone: string | null, website: string | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, logo_url: string | null, logo_data: string | null, primary_color: string | null, secondary_color: string | null, accent_color: string | null, business_settings: string | null, invoice_settings: string | null, industry: string | null, company_size: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateOrganizationRequest = { name: string, slug: string | null, legal_name: string | null, tax_id: string | null, siret: string | null, registration_number: string | null, email: string | null, phone: string | null, website: string | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, industry: string | null, company_size: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateOrganizationRequest = { name: string | null, slug: string | null, legal_name: string | null, tax_id: string | null, siret: string | null, registration_number: string | null, email: string | null, phone: string | null, website: string | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, logo_url: string | null, logo_data: string | null, primary_color: string | null, secondary_color: string | null, accent_color: string | null, business_settings: string | null, invoice_settings: string | null, industry: string | null, company_size: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OnboardingStatus = { completed: boolean, current_step: number, has_organization: boolean, has_admin_user: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OnboardingData = { organization: CreateOrganizationRequest, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrganizationSetting = { key: string, value: string, category: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateOrganizationSettingsRequest = { settings: { [key in string]?: string }, };
