// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

// Quote types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote status enumeration
 */
export type QuoteStatus = "draft" | "sent" | "accepted" | "rejected" | "expired";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote item kind enumeration
 */
export type QuoteItemKind = "labor" | "material" | "service" | "discount";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main Quote entity
 */
export type Quote = { id: string, quote_number: string, client_id: string, task_id: string | null, status: QuoteStatus, valid_until: string | null, notes: string | null, terms: string | null, subtotal: bigint, tax_total: bigint, total: bigint, vehicle_plate: string | null, vehicle_make: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_vin: string | null, created_at: string, updated_at: string, created_by: string | null, 
/**
 * Items included in this quote (populated when loading by ID)
 */
items: Array<QuoteItem>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote item entity
 */
export type QuoteItem = { id: string, quote_id: string, kind: QuoteItemKind, label: string, description: string | null, qty: number, unit_price: bigint, tax_rate: number | null, material_id: string | null, position: number, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote query parameters for listing and filtering
 */
export type QuoteQuery = { page: number | null, limit: number | null, search: string | null, client_id: string | null, status: QuoteStatus | null, date_from: string | null, date_to: string | null, sort_by: string | null, sort_order: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote list response with pagination
 */
export type QuoteListResponse = { data: Array<Quote>, total: bigint, page: number, limit: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create quote request
 */
export type CreateQuoteRequest = { client_id: string, task_id: string | null, valid_until: bigint | null, notes: string | null, terms: string | null, vehicle_plate: string | null, vehicle_make: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_vin: string | null, items: Array<CreateQuoteItemRequest>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update quote request
 */
export type UpdateQuoteRequest = { valid_until: bigint | null, notes: string | null, terms: string | null, vehicle_plate: string | null, vehicle_make: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_vin: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create quote item request
 */
export type CreateQuoteItemRequest = { kind: QuoteItemKind, label: string, description: string | null, qty: number, unit_price: bigint, tax_rate: number | null, material_id: string | null, position: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update quote item request
 */
export type UpdateQuoteItemRequest = { kind: QuoteItemKind | null, label: string | null, description: string | null, qty: number | null, unit_price: bigint | null, tax_rate: number | null, material_id: string | null, position: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for accept action that may create a task
 */
export type QuoteAcceptResponse = { quote: Quote, task_created: TaskCreatedInfo | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Info about a task created from quote acceptance
 */
export type TaskCreatedInfo = { task_id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for PDF export
 */
export type QuoteExportResponse = { file_path: string, };
