// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

import type { Client } from './clients';
import type { Intervention } from './interventions';
import type { Material, Supplier } from './inventory';
import type { EntityType } from './sync';
import type { Task } from './tasks';

// Reports types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Date range for reports
 */
export type DateRange = { start: string, end: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report filters
 */
export type ReportFilters = { technician_ids: Array<string> | null, client_ids: Array<string> | null, statuses: Array<string> | null, priorities: Array<string> | null, ppf_zones: Array<string> | null, vehicle_models: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report types enumeration
 */
export type ReportType = "overview" | "data_explorer" | "tasks" | "technicians" | "clients" | "quality" | "materials" | "geographic" | "seasonal" | "operational_intelligence";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Export formats
 */
export type ExportFormat = "pdf" | "csv" | "excel";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report metadata information
 */
export type ReportMetadata = { title: string, date_range: DateRange, generated_at: string, filters: ReportFilters, total_records: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search result for data explorer
 */
export type SearchResult = { id: string, entity_type: EntityType, title: string, subtitle: string, status: string | null, date: string | null, metadata: { [key in string]?: string }, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search results across multiple entities
 */
export type SearchResults = { tasks: Array<Task>, clients: Array<Client>, interventions: Array<Intervention>, total_results: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search filters for data explorer
 */
export type SearchFilters = { technician_ids: Array<string> | null, client_ids: Array<string> | null, statuses: Array<string> | null, priorities: Array<string> | null, ppf_zones: Array<string> | null, vehicle_models: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search response
 */
export type SearchResponse = { results: Array<SearchResult>, total_count: bigint, has_more: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entity counts for Data Explorer
 */
export type EntityCounts = { tasks: bigint, clients: bigint, interventions: bigint, technicians: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics KPI categories
 */
export type KpiCategory = "operational" | "financial" | "quality" | "efficiency" | "client_satisfaction";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * KPI trend direction
 */
export type TrendDirection = "up" | "down" | "stable" | "unknown";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calculation period
 */
export type CalculationPeriod = "hourly" | "daily" | "weekly" | "monthly";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics KPI definition and current value
 */
export type AnalyticsKpi = { id: string, kpi_name: string, kpi_category: KpiCategory, display_name: string, description: string | null, unit: string | null, calculation_method: string, current_value: number | null, previous_value: number | null, target_value: number | null, trend_direction: TrendDirection | null, last_calculated: string, calculation_period: CalculationPeriod, is_active: boolean, priority: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metric value types
 */
export type MetricValueType = "count" | "percentage" | "currency" | "duration" | "rating";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics metric data point
 */
export type AnalyticsMetric = { id: string, metric_name: string, metric_category: string, value: number, value_type: MetricValueType, dimensions: string | null, timestamp: string, period_start: string, period_end: string, source: string, source_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dashboard types
 */
export type DashboardType = "main" | "operational" | "financial" | "quality" | "custom";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dashboard configuration
 */
export type AnalyticsDashboard = { id: string, name: string, dashboard_type: DashboardType, layout_config: string | null, widget_configs: string | null, filters_config: string | null, user_id: string | null, is_public: boolean, is_default: boolean, is_active: boolean, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chart data point for frontend visualization
 */
export type ChartDataPoint = { label: string, value: number, category: string | null, timestamp: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chart configuration for dashboard widgets
 */
export type ChartConfig = { chart_type: string, title: string, x_axis_label: string | null, y_axis_label: string | null, data: Array<ChartDataPoint>, colors: Array<string> | null, show_legend: boolean, show_grid: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dashboard widget types
 */
export type WidgetType = "kpi_card" | "chart" | "table" | "metric_grid" | "trend_indicator";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dashboard widget configuration
 */
export type DashboardWidget = { id: string, widget_type: WidgetType, title: string, kpi_id: string | null, chart_config: ChartConfig | null, metric_names: Array<string> | null, position: WidgetPosition, size: WidgetSize, refresh_interval: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Widget position on dashboard grid
 */
export type WidgetPosition = { x: number, y: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Widget size on dashboard grid
 */
export type WidgetSize = { width: number, height: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics dashboard data response
 */
export type AnalyticsDashboardData = { dashboard: AnalyticsDashboard, kpis: Array<AnalyticsKpi>, widgets: Array<DashboardWidget>, date_range: DateRange, last_updated: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics time series data for trend charts
 */
export type AnalyticsTimeSeries = { metric_name: string, data_points: Array<ChartDataPoint>, period: string, aggregation: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics summary for quick overview
 */
export type AnalyticsSummary = { total_interventions: bigint, completed_today: bigint, active_technicians: bigint, average_completion_time: number, client_satisfaction_score: number, quality_compliance_rate: number, revenue_this_month: number, inventory_turnover: number, top_performing_technician: string | null, most_common_issue: string | null, last_updated: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Overview report combining all individual reports
 */
export type OverviewReport = { task_completion: TaskCompletionReport, technician_performance: TechnicianPerformanceReport, client_analytics: ClientAnalyticsReport, quality_compliance: QualityComplianceReport, material_usage: MaterialUsageReport, geographic: GeographicReport, seasonal: SeasonalReport, operational_intelligence: OperationalIntelligenceReport, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Geographic analytics report
 */
export type GeographicReport = { metadata: ReportMetadata, heat_map_data: Array<HeatMapPoint>, service_areas: Array<ServiceArea>, geographic_stats: GeographicStats, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Seasonal trend analysis report
 */
export type SeasonalReport = { metadata: ReportMetadata, seasonal_patterns: Array<SeasonalPattern>, weather_correlation: WeatherCorrelation, peak_periods: Array<PeakPeriod>, performance_trends: Array<PerformanceTrend>, completion_predictions: Array<CompletionTimePrediction>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Heat map point for geographic visualization
 */
export type HeatMapPoint = { latitude: number, longitude: number, intensity: number, intervention_count: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Geographic statistics
 */
export type GeographicStats = { total_points: number, unique_locations: number, average_cluster_density: number, coverage_area_km2: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Service area analysis
 */
export type ServiceArea = { center_lat: number, center_lon: number, coverage_radius_km: number, intervention_count: number, unique_clients: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Peak period identification
 */
export type PeakPeriod = { period_type: string, period_value: string, task_volume: bigint, average_completion_time: number, resource_utilization: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Seasonal pattern analysis
 */
export type SeasonalPattern = { season: string, month: number, average_tasks_per_day: number, completion_rate: number, average_duration_minutes: number, common_issue_types: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Weather correlation analysis
 */
export type WeatherCorrelation = { temperature_impact: number, precipitation_impact: number, wind_impact: number, seasonal_adjustment_factor: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task completion report
 */
export type TaskCompletionReport = { metadata: ReportMetadata, summary: TaskCompletionSummary, daily_breakdown: Array<DailyTaskData>, status_distribution: Array<StatusCount>, technician_breakdown: Array<TechnicianTaskData>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task completion summary
 */
export type TaskCompletionSummary = { total_tasks: bigint, completed_tasks: bigint, completion_rate: number, average_duration: number | null, on_time_completion_rate: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Daily task data
 */
export type DailyTaskData = { date: string, total: bigint, completed: bigint, in_progress: bigint, pending: bigint, cancelled: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status count
 */
export type StatusCount = { status: string, count: bigint, percentage: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Technician task data
 */
export type TechnicianTaskData = { technician_id: string, technician_name: string, tasks_completed: bigint, average_time_per_task: number | null, quality_score: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Technician performance report
 */
export type TechnicianPerformanceReport = { metadata: ReportMetadata, technicians: Array<TechnicianPerformance>, benchmarks: PerformanceBenchmarks, trends: Array<PerformanceTrend>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual technician performance
 */
export type TechnicianPerformance = { id: string, name: string, metrics: TechnicianMetrics, trends: Array<PerformanceTrend>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Technician metrics
 */
export type TechnicianMetrics = { tasks_completed: bigint, average_time_per_task: number, quality_score: number, customer_satisfaction: number, utilization_rate: number, efficiency_score: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Performance benchmarks
 */
export type PerformanceBenchmarks = { top_performer_score: number, team_average: number, industry_average: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Performance trend data
 */
export type PerformanceTrend = { period: string, performance_score: number, tasks_completed: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client analytics report
 */
export type ClientAnalyticsReport = { metadata: ReportMetadata, summary: ClientSummary, retention_analysis: RetentionAnalysis, revenue_analysis: RevenueAnalysis, top_clients: Array<ClientPerformance>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client summary
 */
export type ClientSummary = { total_clients: bigint, new_clients_this_period: bigint, returning_clients: bigint, retention_rate: number, average_revenue_per_client: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Retention analysis
 */
export type RetentionAnalysis = { new_client_rate: number, repeat_client_rate: number, churn_rate: number, lifetime_value: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Revenue analysis
 */
export type RevenueAnalysis = { total_revenue: number, revenue_by_client_type: { [key in string]?: number }, average_revenue_per_task: number, revenue_growth_rate: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client performance data
 */
export type ClientPerformance = { id: string, name: string, customer_type: string, total_revenue: number, tasks_completed: bigint, average_revenue_per_task: number, satisfaction_score: number | null, retention_status: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality compliance report
 */
export type QualityComplianceReport = { metadata: ReportMetadata, summary: QualitySummary, quality_trends: Array<QualityTrend>, common_issues: Array<QualityIssue>, compliance_metrics: ComplianceMetrics, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality summary
 */
export type QualitySummary = { overall_quality_score: number, photo_compliance_rate: number, step_completion_accuracy: number, defect_rate: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality trend data
 */
export type QualityTrend = { date: string, quality_score: number, photo_compliance: number, step_accuracy: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality issue
 */
export type QualityIssue = { issue_type: string, count: bigint, percentage: number, severity: string, recommended_action: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compliance metrics
 */
export type ComplianceMetrics = { documentation_completeness: number, photo_quality_score: number, workflow_adherence: number, safety_compliance: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material usage report
 */
export type MaterialUsageReport = { metadata: ReportMetadata, summary: MaterialSummary, consumption_breakdown: Array<ReportMaterialConsumption>, cost_analysis: MaterialCostAnalysis, efficiency_metrics: MaterialEfficiency, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material summary
 */
export type MaterialSummary = { total_material_cost: number, cost_per_task: number, waste_percentage: number, inventory_turnover: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material consumption data for reports
 */
export type ReportMaterialConsumption = { material_id: string, material_name: string, material_type: string, quantity_used: number, unit_cost: number, total_cost: number, waste_quantity: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material cost analysis
 */
export type MaterialCostAnalysis = { cost_by_material_type: { [key in string]?: number }, cost_trends: Array<CostTrend>, supplier_performance: Array<SupplierPerformance>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cost trend data
 */
export type CostTrend = { period: string, material_cost: number, cost_per_task: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supplier performance
 */
export type SupplierPerformance = { supplier_name: string, material_type: string, total_cost: number, quality_score: number, delivery_reliability: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material efficiency metrics
 */
export type MaterialEfficiency = { utilization_rate: number, waste_reduction_rate: number, cost_efficiency_score: number, inventory_optimization: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Export result
 */
export type ExportResult = { download_url: string | null, content: string | null, file_name: string, file_size: bigint, format: ExportFormat, expires_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report generation request
 */
export type ReportRequest = { report_type: ReportType, date_range: DateRange, filters: ReportFilters, format: ExportFormat | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report generation response
 */
export type ReportResponse = { report_id: string, status: ReportStatus, progress: number, estimated_completion: string, result: ExportResult | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report generation status
 */
export type ReportStatus = "pending" | "processing" | "completed" | "failed" | "cancelled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operational intelligence report
 */
export type OperationalIntelligenceReport = { metadata: ReportMetadata, step_bottlenecks: Array<StepBottleneck>, intervention_bottlenecks: Array<InterventionBottleneck>, resource_utilization: Array<ResourceUtilization>, process_efficiency: ProcessEfficiencyMetrics, recommendations: Array<WorkflowRecommendation>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step bottleneck analysis
 */
export type StepBottleneck = { step_number: number, step_name: string, step_type: string, average_duration_minutes: number, median_duration_minutes: number, max_duration_minutes: number, failure_rate: number, rework_rate: number, pause_rate: number, total_occurrences: bigint, bottleneck_severity: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention bottleneck analysis
 */
export type InterventionBottleneck = { intervention_id: string, task_number: string, technician_name: string, vehicle_plate: string, stuck_at_step: number, time_at_current_step_hours: number, total_duration_hours: number, estimated_vs_actual_ratio: number, priority: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual intervention report result
 */
export type InterventionReportResult = { success: boolean, download_url: string | null, file_path: string | null, file_name: string | null, format: string, file_size: bigint | null, generated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resource utilization metrics
 */
export type ResourceUtilization = { technician_id: string, technician_name: string, active_interventions: bigint, completed_today: bigint, average_completion_time_hours: number, utilization_percentage: number, workload_distribution: Array<WorkloadPeriod>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Process efficiency metrics
 */
export type ProcessEfficiencyMetrics = { overall_efficiency_score: number, average_step_completion_time: number, step_success_rate: number, rework_percentage: number, resource_utilization_rate: number, bottleneck_impact_score: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workflow optimization recommendations
 */
export type WorkflowRecommendation = { recommendation_type: string, priority: string, description: string, impact_score: number, implementation_effort: string, affected_steps: Array<number>, affected_technicians: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Completion time prediction result contract shared across reporting/analytics.
 */
export type CompletionTimePrediction = { predicted_duration_minutes: number, confidence_interval: [number, number], factors_influencing: Array<string>, historical_average: number, prediction_accuracy: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workload period breakdown
 */
export type WorkloadPeriod = { period: string, interventions_count: bigint, average_duration_hours: number, };
