// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

// Settings types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { general: GeneralSettings, security: SecuritySettings, notifications: NotificationSettings, appearance: AppearanceSettings, data_management: DataManagementSettings, storage: StorageSettings, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneralSettings = { auto_save: boolean, language: string, timezone: string, date_format: string, currency: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SecuritySettings = { two_factor_enabled: boolean, session_timeout: number, password_min_length: number, password_require_special_chars: boolean, password_require_numbers: boolean, login_attempts_max: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationSettings = { push_notifications: boolean, email_notifications: boolean, sms_notifications: boolean, task_assignments: boolean, task_completions: boolean, system_alerts: boolean, daily_digest: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppearanceSettings = { dark_mode: boolean, primary_color: string, font_size: string, compact_view: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataManagementSettings = { auto_backup: boolean, backup_frequency: string, retention_days: number, export_format: string, compression_enabled: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DatabaseSettings = { connection_status: string, last_backup: string | null, database_size: string, connection_pool_size: number, query_timeout: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntegrationSettings = { api_enabled: boolean, webhook_url: string | null, external_services: Array<string>, sync_interval: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerformanceSettings = { cache_enabled: boolean, cache_size: number, max_concurrent_tasks: number, memory_limit: number, cpu_limit: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupSettings = { auto_backup: boolean, backup_location: string, encryption_enabled: boolean, compression_level: number, include_attachments: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticSettings = { logging_level: string, performance_monitoring: boolean, error_reporting: boolean, health_checks_enabled: boolean, metrics_collection: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemConfiguration = { database: DatabaseSettings, integrations: IntegrationSettings, performance: PerformanceSettings, backup: BackupSettings, diagnostics: DiagnosticSettings, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageSettings = { photo_storage_type: string, local_storage_path: string | null, cloud_provider: string | null, cloud_bucket: string | null, cloud_region: string | null, cloud_access_key: string | null, cloud_secret_key: string | null, auto_sync_photos: boolean, sync_on_wifi_only: boolean, max_photo_size_mb: number, compression_quality: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfileSettings = { full_name: string, email: string, phone: string | null, avatar_url: string | null, notes: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPreferences = { email_notifications: boolean, push_notifications: boolean, task_assignments: boolean, task_updates: boolean, system_alerts: boolean, weekly_reports: boolean, theme: string, language: string, date_format: string, time_format: string, high_contrast: boolean, large_text: boolean, reduce_motion: boolean, screen_reader: boolean, auto_refresh: boolean, refresh_interval: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSecuritySettings = { two_factor_enabled: boolean, session_timeout: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPerformanceSettings = { cache_enabled: boolean, cache_size: number, offline_mode: boolean, sync_on_startup: boolean, background_sync: boolean, image_compression: boolean, preload_data: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAccessibilitySettings = { high_contrast: boolean, large_text: boolean, reduce_motion: boolean, screen_reader: boolean, focus_indicators: boolean, keyboard_navigation: boolean, text_to_speech: boolean, speech_rate: number, font_size: number, color_blind_mode: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserNotificationSettings = { email_enabled: boolean, push_enabled: boolean, in_app_enabled: boolean, task_assigned: boolean, task_updated: boolean, task_completed: boolean, task_overdue: boolean, system_alerts: boolean, maintenance: boolean, security_alerts: boolean, quiet_hours_enabled: boolean, quiet_hours_start: string, quiet_hours_end: string, digest_frequency: string, batch_notifications: boolean, sound_enabled: boolean, sound_volume: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSettings = { profile: UserProfileSettings, preferences: UserPreferences, security: UserSecuritySettings, performance: UserPerformanceSettings, accessibility: UserAccessibilitySettings, notifications: UserNotificationSettings, };
