// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

import type { JsonValue } from './common';

// Sync types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entity types that can be synchronized
 */
export type EntityType = "task" | "client" | "intervention" | "step" | "photo" | "user";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main sync operation structure
 */
export type SyncOperation = { id: bigint | null, operation_type: OperationType, entity_type: EntityType, entity_id: string, data: JsonValue, dependencies: Array<string>, timestamp_utc: string, retry_count: number, max_retries: number, last_error: string | null, status: SyncStatus, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sync operation status
 */
export type SyncStatus = "pending" | "processing" | "completed" | "failed" | "abandoned";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operation types for sync queue
 */
export type OperationType = "create" | "update" | "delete";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metrics for sync queue monitoring
 */
export type SyncQueueMetrics = { pending_operations: bigint, processing_operations: bigint, completed_operations: bigint, failed_operations: bigint, abandoned_operations: bigint, oldest_pending_age_seconds: bigint | null, average_retry_count: number, };
