// AUTO-GENERATED. DO NOT EDIT. Generated by src-tauri/bin/export-types + scripts/write-types.js

// Task types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main Task entity
 */
export type Task = { id: string, task_number: string, title: string, description: string | null, vehicle_plate: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_make: string | null, vin: string | null, ppf_zones: Array<string> | null, custom_ppf_zones: Array<string> | null, status: TaskStatus, priority: TaskPriority, technician_id: string | null, assigned_at: string | null, assigned_by: string | null, scheduled_date: string | null, start_time: string | null, end_time: string | null, date_rdv: string | null, heure_rdv: string | null, template_id: string | null, workflow_id: string | null, workflow_status: string | null, current_workflow_step_id: string | null, started_at: string | null, completed_at: string | null, completed_steps: string | null, client_id: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, external_id: string | null, lot_film: string | null, checklist_completed: boolean, notes: string | null, tags: string | null, estimated_duration: number | null, actual_duration: number | null, created_at: string, updated_at: string, creator_id: string | null, created_by: string | null, updated_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task status enumeration
 */
export type TaskStatus = "draft" | "scheduled" | "in_progress" | "completed" | "cancelled" | "on_hold" | "pending" | "invalid" | "archived" | "failed" | "overdue" | "assigned" | "paused";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task priority enumeration
 */
export type TaskPriority = "low" | "medium" | "high" | "urgent";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task history entry - tracks status changes
 */
export type TaskHistory = { id: string, task_id: string, old_status: string | null, new_status: string, reason: string | null, changed_at: bigint, changed_by: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Assignment status for task assignment validation
 */
export type AssignmentStatus = "assigned" | "available" | "restricted" | "unavailable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Availability status for task availability checks
 */
export type AvailabilityStatus = "available" | "unavailable" | "locked" | "scheduled_conflict" | "material_unavailable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for task assignment check
 */
export type AssignmentCheckResponse = { task_id: string, user_id: string, status: AssignmentStatus, reason: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for task availability check
 */
export type AvailabilityCheckResponse = { task_id: string, status: AvailabilityStatus, reason: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for creating a new task
 */
export type CreateTaskRequest = { vehicle_plate: string, vehicle_model: string, ppf_zones: Array<string>, scheduled_date: string, external_id: string | null, status: TaskStatus | null, technician_id: string | null, start_time: string | null, end_time: string | null, checklist_completed: boolean | null, notes: string | null, title: string | null, vehicle_make: string | null, vehicle_year: string | null, vin: string | null, date_rdv: string | null, heure_rdv: string | null, lot_film: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, custom_ppf_zones: Array<string> | null, template_id: string | null, workflow_id: string | null, task_number: string | null, creator_id: string | null, created_by: string | null, description: string | null, priority: TaskPriority | null, client_id: string | null, estimated_duration: number | null, tags: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for updating a task
 */
export type UpdateTaskRequest = { id: string | null, title: string | null, description: string | null, priority: TaskPriority | null, status: TaskStatus | null, vehicle_plate: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_make: string | null, vin: string | null, ppf_zones: Array<string> | null, custom_ppf_zones: Array<string> | null, client_id: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, external_id: string | null, lot_film: string | null, checklist_completed: boolean | null, scheduled_date: string | null, start_time: string | null, end_time: string | null, date_rdv: string | null, heure_rdv: string | null, template_id: string | null, workflow_id: string | null, estimated_duration: number | null, notes: string | null, tags: string | null, technician_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for task listing
 */
export type TaskQuery = { page: number | null, limit: number | null, status: TaskStatus | null, technician_id: string | null, client_id: string | null, priority: TaskPriority | null, search: string | null, from_date: string | null, to_date: string | null, sort_by: string, sort_order: SortOrder, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task photo information
 */
export type TaskPhoto = { id: string, task_id: string, photo_type: string, file_path: string, file_size: bigint, mime_type: string, url: string, description: string | null, taken_at: bigint | null, created_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sort order for queries
 */
export type SortOrder = "asc" | "desc";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task with full details including related data
 */
export type TaskWithDetails = { id: string, task_number: string, title: string, description: string | null, vehicle_plate: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_make: string | null, vin: string | null, ppf_zones: Array<string> | null, custom_ppf_zones: Array<string> | null, status: TaskStatus, priority: TaskPriority, technician_id: string | null, assigned_at: string | null, assigned_by: string | null, scheduled_date: string | null, start_time: string | null, end_time: string | null, date_rdv: string | null, heure_rdv: string | null, template_id: string | null, workflow_id: string | null, workflow_status: string | null, current_workflow_step_id: string | null, started_at: string | null, completed_at: string | null, completed_steps: string | null, client_id: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, external_id: string | null, lot_film: string | null, checklist_completed: boolean, notes: string | null, tags: string | null, estimated_duration: number | null, actual_duration: number | null, created_at: string, updated_at: string, creator_id: string | null, created_by: string | null, updated_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for deleting a task
 */
export type DeleteTaskRequest = { id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for task listing with pagination
 */
export type TaskListResponse = { data: Array<TaskWithDetails>, pagination: PaginationInfo, statistics: TaskStatistics | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pagination information
 */
export type PaginationInfo = { page: number, limit: number, total: bigint, total_pages: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task statistics
 */
export type TaskStatistics = { total_tasks: number, draft_tasks: number, scheduled_tasks: number, in_progress_tasks: number, completed_tasks: number, cancelled_tasks: number, on_hold_tasks: number, pending_tasks: number, invalid_tasks: number, archived_tasks: number, failed_tasks: number, overdue_tasks: number, assigned_tasks: number, paused_tasks: number, };


// Status types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatusDistribution = { quote: number, scheduled: number, in_progress: number, paused: number, completed: number, cancelled: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatusTransitionRequest = { task_id: string, new_status: string, reason: string | null, correlation_id: string | null, };
