// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntityType } from "./EntityType";

/**
 * Represents an item in the trash.
 */
export type DeletedItem = { id: string, entity_type: EntityType, display_name: string, deleted_at: bigint, deleted_by: string | null, deleted_by_name: string | null, };
