// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enumerates soft-deletable entity kinds. Must stay aligned with trash repository table mappings.
 */
export type EntityType = "Task" | "Client" | "Quote" | "Material" | "Intervention" | "Photo" | "Rapport";
