export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  DASHBOARD: '/dashboard',
  TASKS: '/tasks',
  TASK_DETAIL: (id: string) => `/tasks/${id}`,
  CLIENTS: '/clients',
  CLIENT_DETAIL: (id: string) => `/clients/${id}`,
  CLIENT_EDIT: (id: string) => `/clients/${id}/edit`,
  CLIENT_NEW: '/clients/new',
  SETTINGS: '/configuration',
  CONFIGURATION: '/configuration',
  ADMIN: {
    DASHBOARD: '/admin',
    USERS: '/admin/users',
    SETTINGS: '/admin/settings',
    TASKS: '/admin/tasks',
    AUDIT: '/admin/audit',
    LOGS: '/admin/logs',
    CALENDAR: '/admin/calendar',
    STATISTICS: '/admin/statistics',
    INVALID_TASKS: '/admin/invalid-tasks',
    SOP_AUTO_ASSOCIATION: '/admin/sop-auto-association',
    CHECKLISTS: '/admin/checklists',
    DB_INSPECT: '/admin/db-inspect',
    DATABASE_SETUP: '/admin/database-setup',
    CONFIGURATION: '/admin/configuration',
  },
};
