export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  DASHBOARD: '/dashboard',
  TASKS: '/tasks',
  TASK_DETAIL: (id: string) => `/tasks/${id}`,
  CLIENTS: '/clients',
  CLIENT_DETAIL: (id: string) => `/clients/${id}`,
  CLIENT_EDIT: (id: string) => `/clients/${id}/edit`,
  CLIENT_NEW: '/clients/new',
  SETTINGS: '/configuration',
  CONFIGURATION: '/configuration',
  ADMIN: {
    DASHBOARD: '/admin',
    USERS: '/admin/users',
    SETTINGS: '/admin/settings',
    TASKS: '/admin/tasks',
    ANALYTICS: '/admin/analytics',
    AUDIT: '/admin/audit',
    LOGS: '/admin/logs',
    CALENDAR: '/admin/calendar',
    STATISTICS: '/admin/statistics',
    INVALID_TASKS: '/admin/invalid-tasks',
    SOP_AUTO_ASSOCIATION: '/admin/sop-auto-association',
    CHECKLISTS: '/admin/checklists',
    DB_INSPECT: '/admin/db-inspect',
    DATABASE_SETUP: '/admin/database-setup',
    CONFIGURATION: '/admin/configuration',
  },
  API: {
    AUTH: {
      LOGIN: '/api/auth/login',
      LOGOUT: '/api/auth/logout',
      SESSION: '/api/auth/session',
      SIGNUP: '/api/auth/signup',
    },
    CLIENTS: '/api/clients',
    CLIENT_DETAIL: (id: string) => `/api/clients/${id}`,
    CLIENT_SEARCH: '/api/clients/search',
    CLIENT_STATS: '/api/clients/stats',
    ADMIN: {
      CONFIGURATION: '/api/admin/configuration',
      ANALYTICS: '/api/admin/analytics',
      AUDIT: '/api/admin/audit',
      LOGS: '/api/admin/logs',
      USERS: '/api/admin/users',
      TASKS: '/api/admin/tasks',
      STATISTICS: '/api/admin/statistics',
    },
    SETTINGS: '/api/settings',
    CONFIGURATION: '/api/configuration',
  },
};