// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Standard API error envelope returned to the frontend.
 */
export type ApiError = { message: string, code: string, details: JsonValue | null, };
