// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiError } from "./ApiError";

/**
 * Standard API response envelope.
 */
export type ApiResponse<T> = { success: boolean, message: string | null, error_code: string | null, data: T | null, error: ApiError | null, correlation_id: string | null, };
