// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter parameters for activity queries.
 */
export type AuditActivityFilter = { user_id: string | null, event_type: string | null, resource_type: string | null, start_date?: number, end_date?: number, limit: number | null, offset: number | null, };
