// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response returned to the frontend after a bulk CSV import operation.
 */
export type BulkImportResponse = { total_processed: number, successful: number, failed: number, errors: Array<string>, duplicates_skipped: number, };
