// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for password change.
 *
 * User must provide their current password for verification before setting a new one.
 */
export type ChangePasswordRequest = { currentPassword: string, newPassword: string, };
