// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ClientStat } from "./ClientStat";

/**
 * Client statistics returned by the service
 */
export type ClientStats = { total_clients: number, individual_clients: number, business_clients: number, clients_with_tasks: number, new_clients_this_month: number, top_clients: Array<ClientStat>, };
