// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a material category.
 */
export type CreateMaterialCategoryRequest = { name: string, code: string | null, parent_id: string | null, level: number | null, description: string | null, color: string | null, };
