// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a supplier.
 */
export type CreateSupplierRequest = { name: string, code: string | null, contact_person: string | null, email: string | null, phone: string | null, website: string | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, business_license: string | null, payment_terms: string | null, lead_time_days: number | null, is_preferred: boolean | null, quality_rating: number | null, delivery_rating: number | null, on_time_delivery_rate: number | null, notes: string | null, special_instructions: string | null, };
