// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InventoryTransactionType } from "./InventoryTransactionType";

/**
 * Request to create an inventory transaction.
 */
export type CreateInventoryTransactionRequest = { material_id: string, transaction_type: InventoryTransactionType, quantity: number, reference_number: string | null, reference_type: string | null, notes: string | null, unit_cost: number | null, warehouse_id: string | null, location_from: string | null, location_to: string | null, batch_number: string | null, expiry_date: number | null, quality_status: string | null, intervention_id: string | null, step_id: string | null, };
