// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateNotificationRequest = { user_id: string, type: string, title: string, message: string, entity_type: string, entity_id: string, entity_url: string, correlation_id: string | null, };
