// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialType } from "./MaterialType";
import type { UnitOfMeasure } from "./UnitOfMeasure";

/**
 * Request to create a new material.
 */
export type CreateMaterialRequest = { sku: string, name: string, description: string | null, material_type: MaterialType, category: string | null, subcategory: string | null, category_id: string | null, brand: string | null, model: string | null, specifications: JsonValue | null, unit_of_measure: UnitOfMeasure, current_stock: number | null, minimum_stock: number | null, maximum_stock: number | null, reorder_point: number | null, unit_cost: number | null, currency: string | null, supplier_id: string | null, supplier_name: string | null, supplier_sku: string | null, quality_grade: string | null, certification: string | null, expiry_date: number | null, batch_number: string | null, storage_location: string | null, warehouse_id: string | null, is_active: boolean | null, is_discontinued: boolean | null, };
