// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceInfo = { hostname: string | null, platform: string, arch: string, id: string | null, };
