// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Film type for PPF
 */
export type FilmType = "standard" | "premium" | "matte" | "colored";
