// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Notification } from "./Notification";

export type GetNotificationsResponse = { notifications: Array<Notification>, unread_count: number, };
