// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FilmType } from "./FilmType";
import type { InterventionStatus } from "./InterventionStatus";
import type { InterventionType } from "./InterventionType";
import type { LightingCondition } from "./LightingCondition";
import type { TimestampString } from "./TimestampString";
import type { WeatherCondition } from "./WeatherCondition";
import type { WorkLocation } from "./WorkLocation";

/**
 * Main intervention struct
 */
export type Intervention = { id: string, task_id: string, task_number: string | null, status: InterventionStatus, vehicle_plate: string, vehicle_model: string | null, vehicle_make: string | null, vehicle_year: number | null, vehicle_color: string | null, vehicle_vin: string | null, client_id: string | null, client_name: string | null, client_email: string | null, client_phone: string | null, technician_id: string | null, technician_name: string | null, intervention_type: InterventionType, 
/**
 * Number of completed steps (0-based count, not array index)
 */
current_step: number, completion_percentage: number, ppf_zones_config: Array<string> | null, ppf_zones_extended: JsonValue | null, film_type: FilmType | null, film_brand: string | null, film_model: string | null, scheduled_at: TimestampString, started_at: TimestampString, completed_at: TimestampString, paused_at: TimestampString, estimated_duration: number | null, actual_duration: number | null, weather_condition: WeatherCondition | null, lighting_condition: LightingCondition | null, work_location: WorkLocation | null, temperature_celsius: number | null, humidity_percentage: number | null, start_location_lat: number | null, start_location_lon: number | null, start_location_accuracy: number | null, end_location_lat: number | null, end_location_lon: number | null, end_location_accuracy: number | null, customer_satisfaction: number | null, quality_score: number | null, final_observations: Array<string> | null, customer_signature: string | null, customer_comments: string | null, metadata: JsonValue | null, notes: string | null, special_instructions: string | null, device_info: JsonValue | null, app_version: string | null, synced: boolean, last_synced_at: bigint | null, sync_error: string | null, created_at: bigint, updated_at: bigint, created_by: string | null, updated_by: string | null, };
