// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention status enum
 */
export type InterventionStatus = "pending" | "in_progress" | "paused" | "completed" | "cancelled";
