// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Intervention } from "./Intervention";
import type { InterventionStats } from "./InterventionStats";

/**
 * Discriminated-union response for intervention management IPC commands.
 *
 * Variants correspond to the action requested:
 * - `List` — paginated list of interventions matching the query
 * - `Stats` — aggregate statistics, optionally scoped to a technician
 * - `ByTask` — all interventions belonging to a specific task
 * - `BulkUpdated` — confirmation that a bulk-update operation completed
 */
export type InterventionManagementResponse = { "type": "List", interventions: Array<Intervention>, total: bigint, page: number, limit: number, } | { "type": "Stats", stats: InterventionStats, } | { "type": "ByTask", interventions: Array<Intervention>, } | { "type": "BulkUpdated", updated_count: number, message: string, };
