// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TechnicianInterventionStats } from "./TechnicianInterventionStats";

/**
 * Intervention aggregate statistics (IPC response type).
 */
export type InterventionStats = { total_interventions: bigint, completed_interventions: bigint, in_progress_interventions: bigint, average_completion_time: number | null, technician_stats: Array<TechnicianInterventionStats>, };
