// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepType } from "./StepType";
import type { WorkflowAnomaly } from "./WorkflowAnomaly";
import type { WorkflowIntegrityStatus } from "./WorkflowIntegrityStatus";

export type InterventionWorkflowState = { active_step_id: string | null, active_step_type: StepType | null, active_step_number: number | null, total_steps: number, completed_steps: number, pending_steps: number, in_progress_steps: number, completed_step_ids: Array<string>, next_allowed_step_ids: Array<string>, is_complete: boolean, progress_percentage: number, integrity_status: WorkflowIntegrityStatus, anomalies: Array<WorkflowAnomaly>, };
