// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialConsumptionSummary } from "./MaterialConsumptionSummary";

/**
 * Material consumption summary for an intervention
 */
export type InterventionMaterialSummary = { intervention_id: string, total_materials_used: number, total_cost: number, materials: Array<MaterialConsumptionSummary>, };
