// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StepStatus } from "./StepStatus";
import type { StepType } from "./StepType";
import type { TimestampString } from "./TimestampString";

/**
 * Intervention step struct
 */
export type InterventionStep = { id: string, intervention_id: string, step_number: number, step_name: string, step_type: StepType, step_status: StepStatus, description: string | null, instructions: JsonValue | null, quality_checkpoints: Array<string> | null, is_mandatory: boolean, requires_photos: boolean, min_photos_required: number, max_photos_allowed: number, started_at: TimestampString, completed_at: TimestampString, paused_at: TimestampString, duration_seconds: number | null, estimated_duration_seconds: number | null, step_data: JsonValue | null, collected_data: JsonValue | null, measurements: JsonValue | null, observations: Array<string> | null, photo_count: number, required_photos_completed: boolean, photo_urls: Array<string> | null, validation_data: JsonValue | null, validation_errors: Array<string> | null, validation_score: number | null, requires_supervisor_approval: boolean, approved_by: string | null, approved_at: TimestampString, rejection_reason: string | null, location_lat: number | null, location_lon: number | null, location_accuracy: number | null, device_timestamp: TimestampString, server_timestamp: TimestampString, title: string | null, notes: string | null, synced: boolean, last_synced_at: TimestampString, created_at: bigint, updated_at: bigint, };
