// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterventionProgress } from "./InterventionProgress";
import type { InterventionStep } from "./InterventionStep";

/**
 * TODO: document
 */
export type InterventionProgressResponse = { "type": "Retrieved", progress: InterventionProgress, steps: Array<InterventionStep>, } | { "type": "StepAdvanced", step: InterventionStep, next_step: InterventionStep | null, progress_percentage: number, requirements_completed: Array<string>, } | { "type": "StepProgressSaved", step: InterventionStep, };
