// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InterventionStatus } from "./InterventionStatus";

/**
 * Progress tracking for interventions
 */
export type InterventionProgress = { intervention_id: string, current_step: number, total_steps: number, completed_steps: number, completion_percentage: number, estimated_time_remaining: number | null, status: InterventionStatus, };
