// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Intervention } from "./Intervention";
import type { InterventionStats } from "./InterventionStats";

/**
 * TODO: document
 */
export type InterventionManagementResponse = { "type": "List", interventions: Array<Intervention>, total: bigint, page: number, limit: number, } | { "type": "Stats", stats: InterventionStats, } | { "type": "ByTask", interventions: Array<Intervention>, } | { "type": "BulkUpdated", updated_count: number, message: string, };
