// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention type
 */
export type InterventionType = "ppf" | "ceramic" | "detailing" | "other";
