// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InventoryTransaction } from "./InventoryTransaction";

/**
 * Enhanced inventory statistics
 */
export type InventoryStats = { total_materials: number, active_materials: number, low_stock_materials: number, expired_materials: number, total_value: number, materials_by_category: { [key in string]?: number }, recent_transactions: Array<InventoryTransaction>, stock_turnover_rate: number, average_inventory_age: number, };
