// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InventoryStats } from "./InventoryStats";
import type { LowStockMaterialsResponse } from "./LowStockMaterialsResponse";
import type { Material } from "./Material";

/**
 * Aggregated dashboard payload — S-1 perf: replaces 4 IPC calls with 1.
 */
export type InventoryDashboardData = { materials: Array<Material>, stats: InventoryStats, low_stock: LowStockMaterialsResponse, expired: Array<Material>, };
