// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inventory movement summary
 */
export type InventoryMovementSummary = { material_id: string, material_name: string, total_stock_in: number, total_stock_out: number, net_movement: number, current_stock: number, last_transaction_date: string | null, };
