// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TypeScript-compatible InventoryTransaction
 */
export type InventoryTransactionTS = { id: string, material_id: string, transaction_type: string, quantity: number, previous_stock: number, new_stock: number, reference_number: string | null, reference_type: string | null, notes: string | null, unit_cost: number | null, total_cost: number | null, warehouse_id: string | null, location_from: string | null, location_to: string | null, batch_number: string | null, expiry_date: bigint | null, quality_status: string | null, intervention_id: string | null, step_id: string | null, performed_by: string, performed_at: bigint, created_at: bigint, updated_at: bigint, synced: boolean, last_synced_at: bigint | null, };
