// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transaction types for inventory movements
 */
export type InventoryTransactionType = "stock_in" | "stock_out" | "adjustment" | "transfer" | "waste" | "return";
