// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Issue severity for task defect reporting.
 *
 * Distinct from `TaskPriority` — severity describes the urgency of a
 * reported defect; "critical" is valid here but not in task priority.
 */
export type IssueSeverity = "low" | "medium" | "high" | "critical";
