// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lighting conditions
 */
export type LightingCondition = "natural" | "artificial" | "mixed";
