// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UnitOfMeasure } from "./UnitOfMeasure";

/**
 * TODO: document
 */
export type LowStockMaterial = { material_id: string, sku: string, name: string, unit_of_measure: UnitOfMeasure, current_stock: number, reserved_stock: number, available_stock: number, minimum_stock: number, effective_threshold: number, shortage_quantity: number, };
