// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LowStockMaterial } from "./LowStockMaterial";

/**
 * Paginated response containing low-stock materials and total count.
 */
export type LowStockMaterialsResponse = { items: Array<LowStockMaterial>, total: number, };
