// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material types for PPF workflows
 */
export type MaterialType = "ppf_film" | "adhesive" | "cleaning_solution" | "tool" | "consumable";
