// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material inventory statistics
 */
export type MaterialStats = { total_materials: number, active_materials: number, low_stock_materials: number, expired_materials: number, total_value: number, materials_by_type: { [key in string]?: number }, };
