// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material category for hierarchical organization
 */
export type MaterialCategory = { id: string, name: string, code: string | null, parent_id: string | null, level: number, description: string | null, color: string | null, is_active: boolean, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: string | null, };
