// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of material consumption
 */
export type MaterialConsumptionSummary = { material_id: string, material_name: string, material_type: string, quantity_used: number, unit_cost: number | null, total_cost: number | null, waste_quantity: number, };
