// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TypeScript-compatible MaterialConsumption
 */
export type MaterialConsumptionTS = { id: string, intervention_id: string, material_id: string, step_id: string | null, quantity_used: number, unit_cost: number | null, total_cost: number | null, waste_quantity: number, waste_reason: string | null, batch_used: string | null, expiry_used: bigint | null, quality_notes: string | null, step_number: number | null, recorded_by: string | null, recorded_at: bigint, created_at: bigint, updated_at: bigint, synced: boolean, last_synced_at: bigint | null, };
