// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MaterialType } from "./MaterialType";
import type { UnitOfMeasure } from "./UnitOfMeasure";

/**
 * Material inventory item
 */
export type Material = { id: string, sku: string, name: string, description: string | null, material_type: MaterialType, category: string | null, subcategory: string | null, category_id: string | null, brand: string | null, model: string | null, specifications: any, unit_of_measure: UnitOfMeasure, current_stock: number, minimum_stock: number | null, maximum_stock: number | null, reorder_point: number | null, unit_cost: number | null, currency: string, supplier_id: string | null, supplier_name: string | null, supplier_sku: string | null, quality_grade: string | null, certification: string | null, expiry_date: string | null, batch_number: string | null, serial_numbers: Array<string> | null, is_active: boolean, is_discontinued: boolean, storage_location: string | null, warehouse_id: string | null, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: string | null, };
