// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message priority levels
 */
export type MessagePriority = "Low" | "Normal" | "High" | "Urgent";
