// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message types supported by the system
 */
export type MessageType = "Email" | "Sms" | "InApp";
