// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message entity representing a single message
 */
export type Message = { id: string, message_type: string, sender_id: string | null, recipient_id: string | null, recipient_email: string | null, recipient_phone: string | null, subject: string | null, body: string, template_id: string | null, task_id: string | null, client_id: string | null, status: string, priority: string, scheduled_at: bigint | null, sent_at: bigint | null, read_at: bigint | null, error_message: string | null, metadata: string | null, created_at: bigint, updated_at: bigint, };
