// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create/update a message template
 */
export type MessageTemplateRequest = { name: string, description: string | null, message_type: string, subject: string | null, body: string, variables: Array<string> | null, category: string | null, };
