// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message status enumeration
 */
export type MessageStatus = "Pending" | "Sent" | "Delivered" | "Failed" | "Read";
