// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message template for reusable messages
 */
export type MessageTemplate = { id: string, name: string, description: string | null, message_type: string, subject: string | null, body: string, variables: string | null, category: string, is_active: boolean, created_by: string | null, created_at: bigint, updated_at: bigint, };
