// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Message } from "./Message";

/**
 * Message list response
 */
export type MessageListResponse = { messages: Array<Message>, total: number, has_more: boolean, };
