// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message query filters
 */
export type MessageQuery = { message_type: string | null, sender_id: string | null, recipient_id: string | null, task_id: string | null, client_id: string | null, status: string | null, priority: string | null, date_from: bigint | null, date_to: bigint | null, limit: number | null, offset: number | null, };
