// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User notification preferences
 */
export type NotificationPreferences = { id: string, user_id: string, in_app_enabled: boolean, task_assigned: boolean, task_updated: boolean, task_completed: boolean, task_overdue: boolean, client_created: boolean, client_updated: boolean, system_alerts: boolean, maintenance_notifications: boolean, quiet_hours_enabled: boolean, quiet_hours_start: string | null, quiet_hours_end: string | null, created_at: bigint, updated_at: bigint, };
