// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operation types for sync queue
 */
export type OperationType = "create" | "update" | "delete";
