// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical pagination input parameters — embed in every domain filter/query
 * struct via composition instead of repeating `page`, `page_size`, `sort_by`,
 * `sort_order` on every struct.  Changing pagination behaviour (e.g. adding
 * cursor-based pagination, adding a `sort_by` field) now requires editing
 * ONE struct + the `usePagination()` frontend hook — not 8+ structs.
 *
 * # DEBT-08 / REF-08
 */
export type PaginationParams = { page: number | null, page_size: number | null, sort_by: string | null, sort_order: string | null, };
