// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserActivityRecord } from "./UserActivityRecord";

/**
 * Paginated response for activity queries.
 */
export type PaginatedUserActivity = { records: Array<UserActivityRecord>, total: number, has_more: boolean, };
