// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaginationParams } from "./PaginationParams";
import type { QuoteStatus } from "./QuoteStatus";

/**
 * Quote query parameters for listing and filtering
 */
export type QuoteQuery = { 
/**
 * Shared pagination params (page, page_size, sort_by, sort_order).
 */
pagination: PaginationParams, search: string | null, client_id: string | null, status: QuoteStatus | null, date_from: string | null, date_to: string | null, };
