// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to record material consumption.
 */
export type RecordConsumptionRequest = { intervention_id: string, material_id: string, step_id: string | null, step_number: number | null, quantity_used: number, waste_quantity: number | null, waste_reason: string | null, batch_used: string | null, quality_notes: string | null, recorded_by: string | null, };
