// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single audit event record.
 */
export type SecurityEventRecord = { id: string, event_type: string, user_id: string, action: string, description: string, result: string, timestamp: string, ip_address: string | null, };
