// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A derived security alert.
 */
export type SecurityAlert = { id: string, event_id: string, title: string, description: string, severity: string, timestamp: string, acknowledged: boolean, resolved: boolean, };
