// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Security KPI counters for the admin dashboard.
 */
export type SecurityMetrics = { total_events_today: bigint, critical_alerts_today: bigint, active_brute_force_attempts: bigint, blocked_ips: bigint, failed_auth_attempts_last_hour: bigint, suspicious_activities_detected: bigint, };
