// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to send a notification (used by cross-domain callers and type export).
 */
export type SendNotificationRequest = { user_id: string, notification_type: string, title: string, message: string, entity_type: string, entity_id: string, entity_url: string, correlation_id: string | null, };
