// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kept for backward-compatible IPC responses; session timeout is fixed at 8h.
 */
export type SessionTimeoutConfig = { default_timeout_minutes: number, max_timeout_minutes: number, enforce_timeout: boolean, };
