// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input DTO for the signup flow.
 *
 * Defined in domain/ so both application and infrastructure layers can reference
 * it without creating an upward dependency.
 */
export type SignupRequest = { email: string, first_name: string, last_name: string, password: string, role: string | null, correlation_id: string | null, };
