// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for transitioning a task to a new status.
 */
export type StatusTransitionRequest = { task_id: string, new_status: string, reason: string | null, correlation_id: string | null, };
