// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TODO: document
 */
export type StatusDistribution = { quote: number, scheduled: number, in_progress: number, paused: number, completed: number, cancelled: number, };
