// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step type enum
 */
export type StepType = "inspection" | "preparation" | "installation" | "finalization";
