// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supplier information
 */
export type Supplier = { id: string, name: string, code: string | null, contact_person: string | null, email: string | null, phone: string | null, website: string | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, business_license: string | null, payment_terms: string | null, lead_time_days: number, is_active: boolean, is_preferred: boolean, quality_rating: number | null, delivery_rating: number | null, on_time_delivery_rate: number | null, notes: string | null, special_instructions: string | null, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: string | null, };
