// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metrics for sync queue monitoring
 */
export type SyncQueueMetrics = { pending_operations: bigint, processing_operations: bigint, completed_operations: bigint, failed_operations: bigint, abandoned_operations: bigint, oldest_pending_age_seconds: bigint | null, average_retry_count: number, };
