// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sync operation status
 */
export type SyncStatus = "pending" | "processing" | "completed" | "failed" | "abandoned";
