// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task status enumeration
 */
export type TaskStatus = "draft" | "scheduled" | "in_progress" | "completed" | "cancelled" | "on_hold" | "pending" | "invalid" | "archived" | "failed" | "overdue" | "assigned" | "paused";
