// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task lifecycle status.
 *
 * This enum is shared across domain boundaries (tasks, interventions,
 * clients) and must be kept in sync with the `tasks.status` column values.
 */
export type TaskStatus = "draft" | "scheduled" | "in_progress" | "completed" | "cancelled" | "on_hold" | "pending" | "invalid" | "archived" | "failed" | "overdue" | "assigned" | "paused";
