// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-technician breakdown within `InterventionStats`.
 */
export type TechnicianInterventionStats = { technician_id: string, technician_name: string, total_interventions: bigint, completed_interventions: bigint, average_rating: number | null, };
