// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wrapper type for timestamps that serializes to ISO string
 */
export type TimestampString = bigint | null;
