// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unit of measure for materials
 */
export type UnitOfMeasure = "piece" | "meter" | "liter" | "gram" | "roll";
