// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update mutable fields on an existing intervention.
 *
 * Replaces the previous `serde_json::Value` payload that required manual
 * field extraction (`updates.get("notes").and_then(|v| v.as_str())`) in the
 * application layer. All fields are optional; omitting a field leaves the
 * stored value unchanged.
 *
 * ADR-018: accepted as a direct Tauri command parameter so Tauri handles
 * deserialization automatically — no manual `from_value` step needed.
 */
export type UpdateInterventionRequest = { 
/**
 * Free-form technician notes attached to this intervention.
 */
notes: string | null, 
/**
 * Special handling or client-requested instructions.
 */
special_instructions: string | null, };
