// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update notification preferences
 */
export type UpdateNotificationPreferencesRequest = { email_enabled: boolean | null, sms_enabled: boolean | null, in_app_enabled: boolean | null, task_assigned: boolean | null, task_updated: boolean | null, task_completed: boolean | null, task_overdue: boolean | null, client_created: boolean | null, client_updated: boolean | null, system_alerts: boolean | null, maintenance_notifications: boolean | null, quiet_hours_enabled: boolean | null, quiet_hours_start: string | null, quiet_hours_end: string | null, email_frequency: string | null, email_digest_time: string | null, correlation_id: string | null, };
