// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateNotificationConfigRequest = { quiet_hours_start: string | null, quiet_hours_end: string | null, timezone: string | null, correlation_id: string | null, };
