// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update material stock.
 */
export type UpdateStockRequest = { material_id: string, quantity_change: number, reason: string, recorded_by: string | null, };
