// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for avatar upload.
 */
export type UploadAvatarRequest = { 
/**
 * Base64-encoded image data (without data URL prefix)
 */
avatarData: string, 
/**
 * MIME type (e.g., "image/png", "image/jpeg")
 */
mimeType: string, };
