// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RBAC role assigned to every user account. Determines IPC-level access.
 */
export type UserRole = "admin" | "technician" | "supervisor" | "viewer";
