// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRole } from "./UserRole";

export type UserAccount = { id: string, email: string, username: string, first_name: string, last_name: string, role: UserRole, password_hash: string, salt: string | null, phone: string | null, is_active: boolean, last_login: bigint | null, login_count: number, preferences: string | null, synced: boolean, last_synced_at: string | null, created_at: string, updated_at: string, };
