// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User activity record for the audit page.
 * ADR-012: timestamp is i64 (milliseconds).
 */
export type UserActivityRecord = { id: string, user_id: string, username: string, event_type: string, action: string, resource_type: string | null, resource_id: string | null, description: string, result: string, timestamp: number, ip_address: string | null, };
