// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserRole } from "./UserRole";

/**
 * Local user account — entity with behaviour.
 *
 * Security-sensitive fields (`password_hash`, `salt`) are excluded from
 * serialisation via `#[serde(skip_serializing)]` so they are never sent
 * to the frontend.
 */
export type UserAccount = { id: string, email: string, username: string, first_name: string, last_name: string, role: UserRole, phone: string | null, is_active: boolean, last_login: bigint | null, login_count: number, preferences: string | null, synced: boolean, last_synced_at: string | null, created_at: string, updated_at: string, };
