// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Weather conditions for intervention
 */
export type WeatherCondition = "sunny" | "cloudy" | "rainy" | "foggy" | "windy" | "other";
