// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Work location type
 */
export type WorkLocation = "indoor" | "outdoor" | "semi_covered";
