// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WorkflowAnomalyCode = "no_steps" | "duplicate_step_number" | "missing_step_number" | "multiple_in_progress_steps" | "pending_after_completed_later_step" | "final_step_completed_before_mandatory_steps" | "intervention_status_mismatch" | "legacy_completed_steps_mismatch";
