// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkflowAnomalyCode } from "./WorkflowAnomalyCode";

export type WorkflowAnomaly = { code: WorkflowAnomalyCode, message: string, };
