// @domain:common
// Auto-generated TypeScript types from Rust backend
// Do not edit manually - generated by export-types.rs

// JSON value helpers (mirrors Rust serde_json::Value)
export type JsonPrimitive = string | number | boolean | null;
export type JsonValue = JsonPrimitive | JsonObject | JsonArray;
export type JsonObject = { [key: string]: JsonValue };
export type JsonArray = JsonValue[];

// Error types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Standard API error envelope returned to the frontend.
 */
export type ApiError = { message: string, code: string, details: JsonValue | null, };


// @domain:system
// System command response types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeviceInfo = { hostname: string | null, platform: string, arch: string, id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HealthStatus = { db: boolean, version: string, };


// @domain:auth
// Auth types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Local user account — entity with behaviour.
 *
 * Security-sensitive fields (`password_hash`, `salt`) are excluded from
 * serialisation via `#[serde(skip_serializing)]` so they are never sent
 * to the frontend.
 */
export type UserAccount = { id: string, email: string, username: string, first_name: string, last_name: string, role: UserRole, phone: string | null, is_active: boolean, last_login: bigint | null, login_count: number, preferences: string | null, synced: boolean, last_synced_at: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * RBAC role assigned to every user account. Determines IPC-level access.
 */
export type UserRole = "admin" | "technician" | "supervisor" | "viewer";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A simplified session stored as a UUID in SQLite (no JWT, no 2FA).
 */
export type UserSession = { id: string, user_id: string, username: string, email: string, role: UserRole, token: string, expires_at: string, last_activity: string, created_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Kept for backward-compatible IPC responses; session timeout is fixed at 8h.
 */
export type SessionTimeoutConfig = { default_timeout_minutes: number, max_timeout_minutes: number, enforce_timeout: boolean, };

// Security audit types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Security KPI counters for the admin dashboard.
 */
export type SecurityMetrics = { total_events_today: bigint, critical_alerts_today: bigint, active_brute_force_attempts: bigint, blocked_ips: bigint, failed_auth_attempts_last_hour: bigint, suspicious_activities_detected: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single audit event record.
 */
export type SecurityEventRecord = { id: string, event_type: string, user_id: string, action: string, description: string, result: string, timestamp: string, ip_address: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A derived security alert.
 */
export type SecurityAlert = { id: string, event_id: string, title: string, description: string, severity: string, timestamp: string, acknowledged: boolean, resolved: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User activity record for the audit page.
 * ADR-012: timestamp is i64 (milliseconds).
 */
export type UserActivityRecord = { id: string, user_id: string, username: string, event_type: string, action: string, resource_type: string | null, resource_id: string | null, description: string, result: string, timestamp: number, ip_address: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter parameters for activity queries.
 */
export type AuditActivityFilter = { user_id: string | null, event_type: string | null, resource_type: string | null, start_date?: number, end_date?: number, limit: number | null, offset: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paginated response for activity queries.
 */
export type PaginatedUserActivity = { records: Array<UserActivityRecord>, total: number, has_more: boolean, };


// @domain:calendar
// Event types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calendar event type.
 */
export type EventType = "meeting" | "appointment" | "task" | "reminder" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Event participant.
 */
export type EventParticipant = { id: string, name: string, email: string | null, status: ParticipantStatus, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Participant attendance status.
 */
export type ParticipantStatus = "accepted" | "declined" | "tentative" | "needsaction";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calendar event status.
 */
export type EventStatus = "confirmed" | "tentative" | "cancelled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for creating a calendar event.
 */
export type CreateEventInput = { title: string, description: string | null, startDatetime: string, endDatetime: string, allDay: boolean | null, timezone: string | null, eventType: EventType | null, category: string | null, taskId: string | null, clientId: string | null, technicianId: string | null, location: string | null, meetingLink: string | null, isVirtual: boolean | null, participants: Array<EventParticipant> | null, reminders: Array<number> | null, color: string | null, tags: Array<string> | null, notes: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for updating a calendar event.
 */
export type UpdateEventInput = { title: string | null, description: string | null, startDatetime: string | null, endDatetime: string | null, allDay: boolean | null, timezone: string | null, eventType: EventType | null, category: string | null, taskId: string | null, clientId: string | null, location: string | null, meetingLink: string | null, isVirtual: boolean | null, participants: Array<EventParticipant> | null, status: EventStatus | null, reminders: Array<number> | null, color: string | null, tags: Array<string> | null, notes: string | null, };



// Calendar additional types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calendar event entity.
 */
export type CalendarEvent = { id: string, title: string, description: string | null, startDatetime: string, endDatetime: string, allDay: boolean, timezone: string, eventType: EventType, category: string | null, taskId: string | null, clientId: string | null, technicianId: string | null, location: string | null, meetingLink: string | null, isVirtual: boolean, participants: Array<EventParticipant>, isRecurring: boolean, recurrenceRule: string | null, parentEventId: string | null, reminders: Array<number>, status: EventStatus, color: string | null, tags: Array<string>, notes: string | null, synced: boolean, lastSyncedAt: bigint | null, createdAt: bigint, updatedAt: bigint, createdBy: string | null, updatedBy: string | null, deletedAt: bigint | null, deletedBy: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CalendarTask represents a task with calendar-specific information.
 * Maps to the `calendar_tasks` SQL view.
 */
export type CalendarTask = { id: string, task_number: string, title: string, status: CalendarTaskStatus, priority: CalendarTaskPriority, scheduled_date: string, start_time: string | null, end_time: string | null, vehicle_plate: string | null, vehicle_model: string | null, technician_id: string | null, technician_name: string | null, client_id: string | null, client_name: string | null, estimated_duration: number | null, actual_duration: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task status values mirrored for calendar display.
 *
 * These variants must remain in sync with `tasks::domain::models::task::TaskStatus`.
 */
export type CalendarTaskStatus = "draft" | "scheduled" | "in_progress" | "completed" | "cancelled" | "on_hold" | "pending" | "invalid" | "archived" | "failed" | "overdue" | "assigned" | "paused";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task priority values mirrored for calendar display.
 */
export type CalendarTaskPriority = "low" | "medium" | "high" | "urgent";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calendar filter for tasks.
 */
export type CalendarFilter = { date_range: CalendarDateRange, technician_ids: Array<string> | null, statuses: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conflict detection result.
 */
export type ConflictDetection = { has_conflict: boolean, conflict_type: string | null, conflicting_tasks: Array<CalendarTask>, message: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Date range filter for calendar queries.
 */
export type CalendarDateRange = { start_date: string, end_date: string, };


// @domain:clients
// Client types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main Client entity
 */
export type Client = { id: string, name: string, email: string | null, phone: string | null, customer_type: CustomerType, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, total_tasks: number, active_tasks: number, completed_tasks: number, last_task_date: string | null, created_at: string, updated_at: string, created_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client with associated tasks (TS-exported)
 */
export type ClientWithTasks = { id: string, name: string, email: string | null, phone: string | null, customer_type: CustomerType, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, total_tasks: number, active_tasks: number, completed_tasks: number, last_task_date: string | null, created_at: string, updated_at: string, created_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, tasks: Array<Task> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client query parameters for listing and filtering
 */
export type ClientQuery = { pagination: PaginationParams, search: string | null, customer_type: CustomerType | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Customer type enumeration
 */
export type CustomerType = "individual" | "business";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create client request
 */
export type CreateClientRequest = { name: string, email: string | null, phone: string | null, customer_type: CustomerType, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update client request
 */
export type UpdateClientRequest = { id: string, name: string | null, email: string | null, phone: string | null, customer_type: CustomerType | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client list response with pagination
 */
export type ClientListResponse = { data: Array<Client>, pagination: PaginationInfo, statistics: ClientStatistics | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client statistics (TS-exported, used in IPC responses)
 */
export type ClientStatistics = { total_clients: bigint, individual_clients: bigint, business_clients: bigint, clients_with_tasks: bigint, new_clients_this_month: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client statistics returned by the service
 */
export type ClientStats = { total_clients: number, individual_clients: number, business_clients: number, clients_with_tasks: number, new_clients_this_month: number, top_clients: Array<ClientStat>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual client stat
 */
export type ClientStat = { id: string, name: string, total_tasks: number, };


// @domain:inventory
// Material types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material types for PPF workflows
 */
export type MaterialType = "ppf_film" | "adhesive" | "cleaning_solution" | "tool" | "consumable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unit of measure for materials
 */
export type UnitOfMeasure = "piece" | "meter" | "liter" | "gram" | "roll";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material inventory item
 */
export type Material = { id: string, sku: string, name: string, description: string | null, material_type: MaterialType, category: string | null, subcategory: string | null, category_id: string | null, brand: string | null, model: string | null, specifications: Record<string, unknown> | null, unit_of_measure: UnitOfMeasure, current_stock: number, minimum_stock: number | null, maximum_stock: number | null, reorder_point: number | null, unit_cost: number | null, currency: string, supplier_id: string | null, supplier_name: string | null, supplier_sku: string | null, quality_grade: string | null, certification: string | null, expiry_date: string | null, batch_number: string | null, serial_numbers: Array<string> | null, is_active: boolean, is_discontinued: boolean, is_expired: boolean, is_low_stock: boolean, storage_location: string | null, warehouse_id: string | null, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TypeScript-compatible Material with i64 timestamps
 */
export type MaterialTS = { id: string, sku: string, name: string, description: string | null, material_type: MaterialType, category: string | null, subcategory: string | null, category_id: string | null, brand: string | null, model: string | null, specifications: string | null, unit_of_measure: UnitOfMeasure, current_stock: number, minimum_stock: number | null, maximum_stock: number | null, reorder_point: number | null, unit_cost: number | null, currency: string, supplier_id: string | null, supplier_name: string | null, supplier_sku: string | null, quality_grade: string | null, certification: string | null, expiry_date: bigint | null, batch_number: string | null, serial_numbers: Array<string> | null, is_active: boolean, is_discontinued: boolean, is_expired: boolean, is_low_stock: boolean, storage_location: string | null, warehouse_id: string | null, created_at: bigint, updated_at: bigint, created_by: string | null, updated_by: string | null, deleted_at: bigint | null, deleted_by: string | null, synced: boolean, last_synced_at: bigint | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material consumption record for interventions
 */
export type MaterialConsumption = { id: string, intervention_id: string, material_id: string, step_id: string | null, quantity_used: number, unit_cost: number | null, total_cost: number | null, waste_quantity: number, waste_reason: string | null, batch_used: string | null, expiry_used: string | null, quality_notes: string | null, step_number: number | null, recorded_by: string | null, recorded_at: string, created_at: string, updated_at: string, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TypeScript-compatible MaterialConsumption
 */
export type MaterialConsumptionTS = { id: string, intervention_id: string, material_id: string, step_id: string | null, quantity_used: number, unit_cost: number | null, total_cost: number | null, waste_quantity: number, waste_reason: string | null, batch_used: string | null, expiry_used: bigint | null, quality_notes: string | null, step_number: number | null, recorded_by: string | null, recorded_at: bigint, created_at: bigint, updated_at: bigint, synced: boolean, last_synced_at: bigint | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material inventory statistics
 */
export type MaterialStats = { total_materials: number, active_materials: number, low_stock_materials: number, expired_materials: number, total_value: number, materials_by_type: { [key in string]?: number }, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enhanced inventory statistics
 */
export type InventoryStats = { total_materials: number, active_materials: number, low_stock_materials: number, expired_materials: number, total_value: number, materials_by_category: { [key in string]?: number }, recent_transactions: Array<InventoryTransaction>, stock_turnover_rate: number, average_inventory_age: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inventory transaction record
 */
export type InventoryTransaction = { id: string, material_id: string, transaction_type: InventoryTransactionType, quantity: number, previous_stock: number, new_stock: number, reference_number: string | null, reference_type: string | null, notes: string | null, unit_cost: number | null, total_cost: number | null, warehouse_id: string | null, location_from: string | null, location_to: string | null, batch_number: string | null, expiry_date: string | null, quality_status: string | null, intervention_id: string | null, step_id: string | null, performed_by: string, performed_at: string, created_at: string, updated_at: string, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TypeScript-compatible InventoryTransaction
 */
export type InventoryTransactionTS = { id: string, material_id: string, transaction_type: InventoryTransactionType, quantity: number, previous_stock: number, new_stock: number, reference_number: string | null, reference_type: string | null, notes: string | null, unit_cost: number | null, total_cost: number | null, warehouse_id: string | null, location_from: string | null, location_to: string | null, batch_number: string | null, expiry_date: bigint | null, quality_status: string | null, intervention_id: string | null, step_id: string | null, performed_by: string, performed_at: bigint, created_at: bigint, updated_at: bigint, synced: boolean, last_synced_at: bigint | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transaction types for inventory movements
 */
export type InventoryTransactionType = "stock_in" | "stock_out" | "adjustment" | "transfer" | "waste" | "return";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supplier information
 */
export type Supplier = { id: string, name: string, code: string | null, contact_person: string | null, email: string | null, phone: string | null, website: string | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, business_license: string | null, payment_terms: string | null, lead_time_days: number, is_active: boolean, is_preferred: boolean, quality_rating: number | null, delivery_rating: number | null, on_time_delivery_rate: number | null, notes: string | null, special_instructions: string | null, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material category for hierarchical organization
 */
export type MaterialCategory = { id: string, name: string, code: string | null, parent_id: string | null, level: number, description: string | null, color: string | null, is_active: boolean, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material consumption summary for an intervention
 */
export type InterventionMaterialSummary = { intervention_id: string, total_materials_used: number, total_cost: number, materials: Array<MaterialConsumptionSummary>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of material consumption
 */
export type MaterialConsumptionSummary = { material_id: string, material_name: string, material_type: string, quantity_used: number, unit_cost: number | null, total_cost: number | null, waste_quantity: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inventory movement summary
 */
export type InventoryMovementSummary = { material_id: string, material_name: string, total_stock_in: number, total_stock_out: number, net_movement: number, current_stock: number, last_transaction_date: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material whose available stock is at or below its reorder threshold.
 */
export type LowStockMaterial = { material_id: string, sku: string, name: string, unit_of_measure: UnitOfMeasure, current_stock: number, reserved_stock: number, available_stock: number, minimum_stock: number, effective_threshold: number, shortage_quantity: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paginated response containing low-stock materials and total count.
 */
export type LowStockMaterialsResponse = { items: Array<LowStockMaterial>, total: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregated dashboard payload — S-1 perf: replaces 4 IPC calls with 1.
 */
export type InventoryDashboardData = { materials: Array<Material>, stats: InventoryStats, low_stock: LowStockMaterialsResponse, expired: Array<Material>, };


// @domain:tasks
// Task types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main Task entity
 */
export type Task = { id: string, task_number: string, title: string, description: string | null, vehicle_plate: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_make: string | null, vin: string | null, ppf_zones: Array<string> | null, custom_ppf_zones: Array<string> | null, status: TaskStatus, priority: TaskPriority, technician_id: string | null, assigned_at: string | null, assigned_by: string | null, scheduled_date: string | null, start_time: string | null, end_time: string | null, date_rdv: string | null, heure_rdv: string | null, template_id: string | null, workflow_id: string | null, workflow_status: string | null, current_workflow_step_id: string | null, started_at: string | null, completed_at: string | null, completed_steps: string | null, client_id: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, external_id: string | null, lot_film: string | null, checklist_completed: boolean, notes: string | null, tags: string | null, estimated_duration: number | null, actual_duration: number | null, created_at: string, updated_at: string, creator_id: string | null, created_by: string | null, updated_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task lifecycle status.
 *
 * This enum is shared across domain boundaries (tasks, interventions,
 * clients) and must be kept in sync with the `tasks.status` column values.
 */
export type TaskStatus = "draft" | "scheduled" | "in_progress" | "completed" | "cancelled" | "on_hold" | "pending" | "invalid" | "archived" | "failed" | "overdue" | "assigned" | "paused";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task priority enumeration
 */
export type TaskPriority = "low" | "medium" | "high" | "urgent";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Issue severity for task defect reporting.
 *
 * Distinct from `TaskPriority` — severity describes the urgency of a
 * reported defect; "critical" is valid here but not in task priority.
 */
export type IssueSeverity = "low" | "medium" | "high" | "critical";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task history entry - tracks status changes
 */
export type TaskHistory = { id: string, task_id: string, old_status: string | null, new_status: string, reason: string | null, changed_at: bigint, changed_by: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Assignment status for task assignment validation
 */
export type AssignmentStatus = "assigned" | "available" | "restricted" | "unavailable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Availability status for task availability checks
 */
export type AvailabilityStatus = "available" | "unavailable" | "locked" | "scheduled_conflict" | "material_unavailable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for task assignment check
 */
export type AssignmentCheckResponse = { task_id: string, user_id: string, status: AssignmentStatus, reason: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for task availability check
 */
export type AvailabilityCheckResponse = { task_id: string, status: AvailabilityStatus, reason: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for creating a new task
 */
export type CreateTaskRequest = { vehicle_plate: string, vehicle_model: string, ppf_zones: Array<string>, scheduled_date: string, external_id: string | null, status: TaskStatus | null, technician_id: string | null, start_time: string | null, end_time: string | null, checklist_completed: boolean | null, notes: string | null, title: string | null, vehicle_make: string | null, vehicle_year: string | null, vin: string | null, date_rdv: string | null, heure_rdv: string | null, lot_film: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, custom_ppf_zones: Array<string> | null, template_id: string | null, workflow_id: string | null, task_number: string | null, creator_id: string | null, created_by: string | null, description: string | null, priority: TaskPriority | null, client_id: string | null, estimated_duration: number | null, tags: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for updating a task
 */
export type UpdateTaskRequest = { id: string | null, title: string | null, description: string | null, priority: TaskPriority | null, status: TaskStatus | null, vehicle_plate: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_make: string | null, vin: string | null, ppf_zones: Array<string> | null, custom_ppf_zones: Array<string> | null, client_id: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, external_id: string | null, lot_film: string | null, checklist_completed: boolean | null, scheduled_date: string | null, start_time: string | null, end_time: string | null, date_rdv: string | null, heure_rdv: string | null, template_id: string | null, workflow_id: string | null, estimated_duration: number | null, notes: string | null, tags: string | null, technician_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single checklist item belonging to a task.
 */
export type ChecklistItem = { id: string, task_id: string, description: string, position: number, is_completed: boolean, completed_at: string | null, completed_by: string | null, notes: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create a new checklist item for a task.
 */
export type CreateChecklistItemRequest = { task_id: string, description: string, position: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update the completion state of a checklist item.
 */
export type UpdateChecklistItemRequest = { is_completed: boolean, notes: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for task listing
 */
export type TaskQuery = { 
/**
 * Shared pagination params (page, page_size, sort_by, sort_order).
 */
pagination: PaginationParams, status: TaskStatus | null, technician_id: string | null, client_id: string | null, priority: TaskPriority | null, search: string | null, from_date: string | null, to_date: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task photo information
 */
export type TaskPhoto = { id: string, task_id: string, photo_type: string, file_path: string, file_size: bigint, mime_type: string, url: string, description: string | null, taken_at: bigint | null, created_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sort order for queries
 */
export type SortOrder = "asc" | "desc";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task with full details including related data
 */
export type TaskWithDetails = { id: string, task_number: string, title: string, description: string | null, vehicle_plate: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_make: string | null, vin: string | null, ppf_zones: Array<string> | null, custom_ppf_zones: Array<string> | null, status: TaskStatus, priority: TaskPriority, technician_id: string | null, assigned_at: string | null, assigned_by: string | null, scheduled_date: string | null, start_time: string | null, end_time: string | null, date_rdv: string | null, heure_rdv: string | null, template_id: string | null, workflow_id: string | null, workflow_status: string | null, current_workflow_step_id: string | null, started_at: string | null, completed_at: string | null, completed_steps: string | null, client_id: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, external_id: string | null, lot_film: string | null, checklist_completed: boolean, notes: string | null, tags: string | null, estimated_duration: number | null, actual_duration: number | null, created_at: string, updated_at: string, creator_id: string | null, created_by: string | null, updated_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for deleting a task
 */
export type DeleteTaskRequest = { id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for task listing with pagination
 */
export type TaskListResponse = { data: Array<TaskWithDetails>, pagination: PaginationInfo, statistics: TaskStatistics | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pagination metadata
 */
export type PaginationInfo = { page: number, limit: number, total: bigint, total_pages: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Canonical pagination input parameters — embed in every domain filter/query
 * struct via composition instead of repeating `page`, `page_size`, `sort_by`,
 * `sort_order` on every struct.  Changing pagination behaviour (e.g. adding
 * cursor-based pagination, adding a `sort_by` field) now requires editing
 * ONE struct + the `usePagination()` frontend hook — not 8+ structs.
 *
 * # DEBT-08 / REF-08
 */
export type PaginationParams = { page: number | null, page_size: number | null, sort_by: string | null, sort_order: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task statistics
 */
export type TaskStatistics = { total_tasks: number, draft_tasks: number, scheduled_tasks: number, in_progress_tasks: number, completed_tasks: number, cancelled_tasks: number, on_hold_tasks: number, pending_tasks: number, invalid_tasks: number, archived_tasks: number, failed_tasks: number, overdue_tasks: number, assigned_tasks: number, paused_tasks: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response returned to the frontend after a bulk CSV import operation.
 */
export type BulkImportResponse = { total_processed: number, successful: number, failed: number, errors: Array<string>, duplicates_skipped: number, };


// @domain:common
// Repository types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paginated result
 */
export type PaginatedResult<T> = { data: Array<T>, pagination: PaginationInfo, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cache statistics
 */
export type CacheStats = { size: number, };


// @domain:documents
// Photo types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Represents a shared intervention photo record. Carries storage, metadata, and approval fields.
 */
export type Photo = { id: string, intervention_id: string, step_id: string | null, step_number: number | null, file_path: string, file_name: string | null, file_size: bigint | null, mime_type: string, width: number | null, height: number | null, photo_type: PhotoType | null, photo_category: PhotoCategory | null, photo_angle: string | null, zone: string | null, title: string | null, description: string | null, notes: string | null, annotations: JsonValue | null, gps_location_lat: number | null, gps_location_lon: number | null, gps_location_accuracy: number | null, quality_score: number | null, blur_score: number | null, exposure_score: number | null, composition_score: number | null, is_required: boolean, is_approved: boolean, approved_by: string | null, approved_at: bigint | null, rejection_reason: string | null, synced: boolean, storage_url: string | null, upload_retry_count: number, upload_error: string | null, last_synced_at: bigint | null, captured_at: bigint | null, uploaded_at: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies a photo by workflow timing. Stored as lowercase strings across IPC and SQLite.
 */
export type PhotoType = "before" | "during" | "after";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Classifies a photo by capture purpose. Stored as snake_case strings across IPC and SQLite.
 */
export type PhotoCategory = "vehicle_condition" | "workspace" | "step_progress" | "qc_check" | "final_result" | "other";


// @domain:quotes
// Quote types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote status enumeration
 */
export type QuoteStatus = "draft" | "sent" | "accepted" | "rejected" | "expired" | "converted" | "changes_requested";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote item kind enumeration
 */
export type QuoteItemKind = "labor" | "material" | "service" | "discount";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main Quote entity
 */
export type Quote = { id: string, quote_number: string, client_id: string, task_id: string | null, status: QuoteStatus, valid_until: string | null, 
/**
 * Public-facing description (shown to customer)
 */
description: string | null, 
/**
 * Internal notes (only visible to staff)
 */
notes: string | null, terms: string | null, subtotal: bigint, tax_total: bigint, total: bigint, discount_type: string | null, discount_value: bigint | null, discount_amount: bigint | null, vehicle_plate: string | null, vehicle_make: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_vin: string | null, created_at: string, updated_at: string, created_by: string | null, 
/**
 * Items included in this quote (populated when loading by ID)
 */
items: Array<QuoteItem>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote item entity
 */
export type QuoteItem = { id: string, quote_id: string, kind: QuoteItemKind, label: string, description: string | null, qty: number, unit_price: bigint, tax_rate: number | null, material_id: string | null, position: number, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote query parameters for listing and filtering
 */
export type QuoteQuery = { 
/**
 * Shared pagination params (page, page_size, sort_by, sort_order).
 */
pagination: PaginationParams, search: string | null, clientId: string | null, status: QuoteStatus | null, dateFrom: string | null, dateTo: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote list response with pagination
 */
export type QuoteListResponse = { data: Array<Quote>, total: bigint, page: number, limit: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One month's quote count.
 */
export type QuoteMonthlyCount = { 
/**
 * e.g. "2026-03"
 */
month: string, count: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Aggregate statistics for all quotes (not limited by pagination).
 */
export type QuoteStats = { total: bigint, draft: bigint, sent: bigint, accepted: bigint, rejected: bigint, expired: bigint, converted: bigint, 
/**
 * Monthly counts for the last 6 months: each entry is (year_month, count).
 */
monthly_counts: Array<QuoteMonthlyCount>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create quote request
 */
export type CreateQuoteRequest = { client_id: string, task_id: string | null, valid_until: bigint | null, description: string | null, notes: string | null, terms: string | null, discount_type: string | null, discount_value: bigint | null, vehicle_plate: string | null, vehicle_make: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_vin: string | null, items: Array<CreateQuoteItemRequest>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update quote request
 */
export type UpdateQuoteRequest = { valid_until: bigint | null, description: string | null, notes: string | null, terms: string | null, discount_type: string | null, discount_value: bigint | null, vehicle_plate: string | null, vehicle_make: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_vin: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create quote item request
 */
export type CreateQuoteItemRequest = { kind: QuoteItemKind, label: string, description: string | null, qty: number, unit_price: bigint, tax_rate: number | null, material_id: string | null, position: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update quote item request
 */
export type UpdateQuoteItemRequest = { kind: QuoteItemKind | null, label: string | null, description: string | null, qty: number | null, unit_price: bigint | null, tax_rate: number | null, material_id: string | null, position: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for accept action that may create a task
 */
export type QuoteAcceptResponse = { quote: Quote, task_created: TaskCreatedInfo | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Info about a task created from quote acceptance
 */
export type TaskCreatedInfo = { task_id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for PDF export
 */
export type QuoteExportResponse = { file_path: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Attachment type enumeration for quote attachments
 */
export type AttachmentType = "image" | "document" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quote attachment entity
 */
export type QuoteAttachment = { id: string, quote_id: string, file_name: string, file_path: string, file_size: bigint, mime_type: string, attachment_type: AttachmentType, description: string | null, created_at: string, created_by: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create quote attachment request
 */
export type CreateQuoteAttachmentRequest = { file_name: string, file_path: string, file_size: bigint, mime_type: string, attachment_type: AttachmentType | null, description: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update quote attachment request
 */
export type UpdateQuoteAttachmentRequest = { description: string | null, attachment_type: AttachmentType | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for convert-to-task action
 */
export type ConvertQuoteToTaskResponse = { quote: Quote, task_id: string, task_number: string, };


// @domain:interventions
// Intervention types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main intervention struct
 */
export type Intervention = { id: string, task_id: string, task_number: string | null, status: InterventionStatus, vehicle_plate: string, vehicle_model: string | null, vehicle_make: string | null, vehicle_year: number | null, vehicle_color: string | null, vehicle_vin: string | null, client_id: string | null, client_name: string | null, client_email: string | null, client_phone: string | null, technician_id: string | null, technician_name: string | null, intervention_type: InterventionType, 
/**
 * Number of completed steps (0-based count, not array index)
 */
current_step: number, completion_percentage: number, ppf_zones_config: Array<string> | null, ppf_zones_extended: JsonValue | null, film_type: FilmType | null, film_brand: string | null, film_model: string | null, scheduled_at: TimestampString, started_at: TimestampString, completed_at: TimestampString, paused_at: TimestampString, estimated_duration: number | null, actual_duration: number | null, weather_condition: WeatherCondition | null, lighting_condition: LightingCondition | null, work_location: WorkLocation | null, temperature_celsius: number | null, humidity_percentage: number | null, start_location_lat: number | null, start_location_lon: number | null, start_location_accuracy: number | null, end_location_lat: number | null, end_location_lon: number | null, end_location_accuracy: number | null, customer_satisfaction: number | null, quality_score: number | null, final_observations: Array<string> | null, customer_signature: string | null, customer_comments: string | null, metadata: JsonValue | null, notes: string | null, special_instructions: string | null, device_info: JsonValue | null, app_version: string | null, synced: boolean, last_synced_at: bigint | null, sync_error: string | null, created_at: bigint, updated_at: bigint, created_by: string | null, updated_by: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention status enum
 */
export type InterventionStatus = "pending" | "in_progress" | "paused" | "completed" | "cancelled" | "archived";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention type
 */
export type InterventionType = "ppf" | "ceramic" | "detailing" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter for intervention queries
 */
export type InterventionFilter = { task_id: string | null, status: string | null, technician_id: string | null, client_id: string | null, priority: string | null, from_date: string | null, to_date: string | null, intervention_type: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for bulk updating interventions
 */
export type BulkUpdateInterventionRequest = { intervention_ids: Array<string>, status: string | null, technician_id: string | null, priority: string | null, updates: string | null, };

// @domain:common
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GPS coordinates
 */
export type GpsLocation = { latitude: number, longitude: number, accuracy: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Film type for PPF
 */
export type FilmType = "standard" | "premium" | "matte" | "colored";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Weather conditions for intervention
 */
export type WeatherCondition = "sunny" | "cloudy" | "rainy" | "foggy" | "windy" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lighting conditions
 */
export type LightingCondition = "natural" | "artificial" | "mixed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Work location type
 */
export type WorkLocation = "indoor" | "outdoor" | "semi_covered";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wrapper type for timestamps that serializes to ISO string
 */
export type TimestampString = bigint | null;

// @domain:interventions
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GPS coordinates for location tracking
 */
export type GpsCoordinates = { latitude: number, longitude: number, accuracy: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention step struct
 */
export type InterventionStep = { id: string, intervention_id: string, step_number: number, step_name: string, step_type: StepType, step_status: StepStatus, description: string | null, instructions: JsonValue | null, quality_checkpoints: Array<string> | null, is_mandatory: boolean, requires_photos: boolean, min_photos_required: number, max_photos_allowed: number, started_at: TimestampString, completed_at: TimestampString, paused_at: TimestampString, duration_seconds: number | null, estimated_duration_seconds: number | null, step_data: JsonValue | null, collected_data: JsonValue | null, measurements: JsonValue | null, observations: Array<string> | null, photo_count: number, required_photos_completed: boolean, photo_urls: Array<string> | null, validation_data: JsonValue | null, validation_errors: Array<string> | null, validation_score: number | null, requires_supervisor_approval: boolean, approved_by: string | null, approved_at: TimestampString, rejection_reason: string | null, location_lat: number | null, location_lon: number | null, location_accuracy: number | null, device_timestamp: TimestampString, server_timestamp: TimestampString, title: string | null, notes: string | null, synced: boolean, last_synced_at: TimestampString, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step type enum
 */
export type StepType = "inspection" | "preparation" | "installation" | "finalization";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to start a new intervention
 */
export type StartInterventionRequest = { task_id: string, intervention_number: string | null, ppf_zones: Array<string>, custom_zones: Array<string> | null, film_type: string, film_brand: string | null, film_model: string | null, weather_condition: string, lighting_condition: string, work_location: string, temperature: number | null, humidity: number | null, technician_id: string, assistant_ids: Array<string> | null, 
/**
 * // TODO: ADR Violation (ADR-012) - scheduled_start should be i64 (milliseconds)
 */
scheduled_start: string, estimated_duration: number, gps_coordinates: GpsCoordinates | null, address: string | null, notes: string | null, customer_requirements: Array<string> | null, special_instructions: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to advance a step
 */
export type AdvanceStepRequest = { intervention_id: string, step_id: string, collected_data: JsonValue, photos: Array<string> | null, notes: string | null, quality_check_passed: boolean, issues: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for saving step progress without advancing
 */
export type SaveStepProgressRequest = { step_id: string, collected_data: JsonValue, notes: string | null, photos: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to finalize an intervention
 */
export type FinalizeInterventionRequest = { intervention_id: string, collected_data: JsonValue | null, photos: Array<string> | null, customer_satisfaction: number | null, quality_score: number | null, final_observations: Array<string> | null, customer_signature: string | null, customer_comments: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update mutable fields on an existing intervention.
 *
 * Replaces the previous `serde_json::Value` payload that required manual
 * field extraction (`updates.get("notes").and_then(|v| v.as_str())`) in the
 * application layer. All fields are optional; omitting a field leaves the
 * stored value unchanged.
 *
 * ADR-018: accepted as a direct Tauri command parameter so Tauri handles
 * deserialization automatically — no manual `from_value` step needed.
 */
export type UpdateInterventionRequest = { 
/**
 * Free-form technician notes attached to this intervention.
 */
notes: string | null, 
/**
 * Special handling or client-requested instructions.
 */
special_instructions: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for starting an intervention
 */
export type StartInterventionResponse = { intervention: Intervention, steps: Array<InterventionStep>, initial_requirements: Array<StepRequirement>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for advancing a step
 */
export type AdvanceStepResponse = { step: InterventionStep, next_step: InterventionStep | null, progress_percentage: number, requirements_completed: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for saving step progress
 */
export type SaveStepProgressResponse = { step: InterventionStep, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for finalizing an intervention
 */
export type FinalizeInterventionResponse = { intervention: Intervention, metrics: InterventionMetrics, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step requirement for workflow validation
 */
export type StepRequirement = { step_id: string, requirement_type: string, description: string, is_mandatory: boolean, is_completed: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention step with associated photos
 */
export type InterventionStepWithPhotos = { step: InterventionStep, photos: Array<Photo>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention with all related data
 */
export type InterventionWithDetails = { intervention: Intervention, steps: Array<InterventionStepWithPhotos>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress tracking for interventions
 */
export type InterventionProgress = { intervention_id: string, current_step: number, total_steps: number, completed_steps: number, completion_percentage: number, estimated_time_remaining: number | null, status: InterventionStatus, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention metrics for finalization
 */
export type InterventionMetrics = { total_duration_minutes: number, completion_rate: number, quality_score: number | null, customer_satisfaction: number | null, steps_completed: number, total_steps: number, photos_taken: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step status enum
 */
export type StepStatus = "pending" | "in_progress" | "paused" | "completed" | "failed" | "skipped" | "rework";

// Intervention IPC response types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-technician breakdown within `InterventionStats`.
 */
export type TechnicianInterventionStats = { technician_id: string, technician_name: string, total_interventions: bigint, completed_interventions: bigint, average_rating: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention aggregate statistics (IPC response type).
 */
export type InterventionStats = { total_interventions: bigint, completed_interventions: bigint, in_progress_interventions: bigint, average_completion_time: number | null, technician_stats: Array<TechnicianInterventionStats>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminated-union response for intervention management IPC commands.
 *
 * Variants correspond to the action requested:
 * - `List` — paginated list of interventions matching the query
 * - `Stats` — aggregate statistics, optionally scoped to a technician
 * - `ByTask` — all interventions belonging to a specific task
 * - `BulkUpdated` — confirmation that a bulk-update operation completed
 */
export type InterventionManagementResponse = { "type": "List", interventions: Array<Intervention>, total: bigint, page: number, limit: number, } | { "type": "Stats", stats: InterventionStats, } | { "type": "ByTask", interventions: Array<Intervention>, } | { "type": "BulkUpdated", updated_count: number, message: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminated-union response for intervention progress/step IPC commands.
 *
 * Variants correspond to the action requested:
 * - `Retrieved` — current progress and all steps for an intervention
 * - `StepAdvanced` — result after advancing to the next step
 * - `StepProgressSaved` — confirmation that step progress was persisted
 */
export type InterventionProgressResponse = { "type": "Retrieved", progress: InterventionProgress, steps: Array<InterventionStep>, } | { "type": "StepAdvanced", step: InterventionStep, next_step: InterventionStep | null, progress_percentage: number, requirements_completed: Array<string>, } | { "type": "StepProgressSaved", step: InterventionStep, };

// @domain:notifications
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Notification = { id: string, created_at: bigint, type: string, title: string, message: string, entity_type: string, entity_id: string, entity_url: string, read: boolean, user_id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationChannel = "InApp";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationType = "TaskAssignment" | "TaskUpdate" | "TaskCompletion" | "StatusChange" | "OverdueWarning" | "SystemAlert" | "NewAssignment" | "DeadlineReminder" | "QualityApproval";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationTemplate = { id: string, name: string, notification_type: NotificationType, channel: NotificationChannel, subject_template: string, body_template: string, variables: Array<string>, is_active: boolean, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationMessage = { id: string, user_id: string, notification_type: NotificationType, channel: NotificationChannel, recipient: string, subject: string | null, body: string, priority: NotificationPriority, status: NotificationStatus, scheduled_at: bigint | null, sent_at: bigint | null, error_message: string | null, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationPriority = "Low" | "Normal" | "High" | "Critical";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationStatus = "Pending" | "Sent" | "Failed" | "Cancelled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TemplateVariables = { user_name: string | null, task_title: string | null, task_id: string | null, client_name: string | null, due_date: string | null, status: string | null, priority: string | null, assignee_name: string | null, system_message: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationConfig = { quiet_hours_start: string | null, quiet_hours_end: string | null, timezone: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateNotificationConfigRequest = { quiet_hours_start: string | null, quiet_hours_end: string | null, timezone: string | null, correlation_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to send a notification (used by cross-domain callers and type export).
 */
export type SendNotificationRequest = { user_id: string, notification_type: string, title: string, message: string, entity_type: string, entity_id: string, entity_url: string, correlation_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Message = { id: string, message_type: string, sender_id: string | null, recipient_id: string | null, recipient_email: string | null, recipient_phone: string | null, subject: string | null, body: string, template_id: string | null, task_id: string | null, client_id: string | null, status: string, priority: string, scheduled_at: bigint | null, sent_at: bigint | null, read_at: bigint | null, error_message: string | null, metadata: string | null, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageType = "Email" | "Sms" | "InApp";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageStatus = "Pending" | "Sent" | "Delivered" | "Failed" | "Read";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessagePriority = "Low" | "Normal" | "High" | "Urgent";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageQuery = { message_type: string | null, sender_id: string | null, recipient_id: string | null, task_id: string | null, client_id: string | null, status: string | null, priority: string | null, date_from: bigint | null, date_to: bigint | null, limit: number | null, offset: number | null, correlation_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageListResponse = { messages: Array<Message>, total: number, has_more: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageTemplate = { id: string, name: string, description: string | null, message_type: string, subject: string | null, body: string, variables: string | null, category: string, is_active: boolean, created_by: string | null, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MessageTemplateRequest = { name: string, description: string | null, message_type: string, subject: string | null, body: string, variables: Array<string> | null, category: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SendMessageRequest = { message_type: string, recipient_id: string | null, recipient_email: string | null, recipient_phone: string | null, subject: string | null, body: string, template_id: string | null, task_id: string | null, client_id: string | null, priority: string | null, scheduled_at: bigint | null, correlation_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationPreferences = { id: string, user_id: string, in_app_enabled: boolean, task_assigned: boolean, task_updated: boolean, task_completed: boolean, task_overdue: boolean, client_created: boolean, client_updated: boolean, system_alerts: boolean, maintenance_notifications: boolean, quiet_hours_enabled: boolean, quiet_hours_start: string | null, quiet_hours_end: string | null, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateNotificationPreferencesRequest = { in_app_enabled: boolean | null, task_assigned: boolean | null, task_updated: boolean | null, task_completed: boolean | null, task_overdue: boolean | null, client_created: boolean | null, client_updated: boolean | null, system_alerts: boolean | null, maintenance_notifications: boolean | null, quiet_hours_enabled: boolean | null, quiet_hours_start: string | null, quiet_hours_end: string | null, correlation_id: string | null, };

// @domain:auth
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request DTO for creating a user.
 */
export type CreateUserRequest = { email: string, first_name: string, last_name: string, role: string, password: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request DTO for updating a user.
 */
export type UpdateUserRequest = { email: string | null, first_name: string | null, last_name: string | null, role: string | null, is_active: boolean | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Domain-level user management action.
 */
export type UserAction = { "action": "Create", data: CreateUserRequest, } | { "action": "Get", id: string, } | { "action": "Update", id: string, data: UpdateUserRequest, } | { "action": "Delete", id: string, } | { "action": "List", limit: number | null, offset: number | null, search: string | null, role_filter: string | null, } | { "action": "ChangePassword", id: string, new_password: string, } | { "action": "ChangeRole", id: string, new_role: UserRole, } | { "action": "Ban", id: string, } | { "action": "Unban", id: string, } | { "action": "AdminResetPassword", id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * TODO: document
 */
export type UserListResponse = { data: Array<UserAccount>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Discriminated-union IPC response for user CRUD commands.
 *
 * Variants map to the action that was executed:
 * `Created`, `Found`, `Updated`, `Deleted`, `NotFound`, `List`,
 * `PasswordChanged`, `RoleChanged`, `UserBanned`, `UserUnbanned`.
 */
export type UserResponse = { "type": "Created" } & UserAccount | { "type": "Found" } & UserAccount | { "type": "Updated" } & UserAccount | { "type": "Deleted" } | { "type": "NotFound" } | { "type": "List" } & UserListResponse | { "type": "PasswordChanged" } | { "type": "RoleChanged" } | { "type": "UserBanned" } | { "type": "UserUnbanned" } | { "type": "PasswordReset" } & string;


// @domain:navigation
// Global Search types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GlobalSearchResult = { "type": "task", id: string, task_number: string, title: string, status: string, } | { "type": "client", id: string, name: string, email: string | null, } | { "type": "material", id: string, name: string, sku: string, } | { "type": "quote", id: string, quote_number: string, description: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GlobalSearchResponse = { results: Array<GlobalSearchResult>, };


// @domain:tasks
// Status types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts of tasks grouped by workflow status, used for dashboard widgets.
 */
export type StatusDistribution = { quote: number, scheduled: number, in_progress: number, paused: number, completed: number, cancelled: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request payload for transitioning a task to a new status.
 */
export type StatusTransitionRequest = { task_id: string, new_status: string, reason: string | null, correlation_id: string | null, };


// @domain:sync
// Sync types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entity types that can be synchronized
 */
export type EntityType = "task" | "client" | "intervention" | "step" | "photo" | "user";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main sync operation structure
 */
export type SyncOperation = { operation_type: OperationType, entity_type: EntityType, entity_id: string, data: JsonValue, dependencies: Array<string>, timestamp_utc: string, retry_count: number, max_retries: number, last_error: string | null, status: SyncStatus, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sync operation status
 */
export type SyncStatus = "pending" | "processing" | "completed" | "failed" | "abandoned";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operation types for sync queue
 */
export type OperationType = "create" | "update" | "delete";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metrics for sync queue monitoring
 */
export type SyncQueueMetrics = { pending_operations: bigint, processing_operations: bigint, completed_operations: bigint, failed_operations: bigint, abandoned_operations: bigint, oldest_pending_age_seconds: bigint | null, average_retry_count: number, };


// @domain:reports
// Reports types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ReportCapabilities = { version: string, status: string, available_exports: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InterventionReport = { id: string, intervention_id: string, report_number: string, generated_at: bigint, technician_id: string | null, technician_name: string | null, file_path: string | null, file_name: string | null, file_size: bigint | null, format: string, status: string, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InterventionReportResult = { success: boolean, download_url: string | null, file_path: string | null, file_name: string | null, format: string, file_size: bigint | null, generated_at: bigint, };


// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Completion time prediction result contract shared across reporting/analytics.
 */
export type CompletionTimePrediction = { predicted_duration_minutes: number, confidence_interval: [number, number], factors_influencing: Array<string>, historical_average: number, prediction_accuracy: number, };

// @domain:settings
// Settings types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { general: GeneralSettings, security: SecuritySettings, notifications: NotificationSettings, appearance: AppearanceSettings, data_management: DataManagementSettings, storage: StorageSettings, business_rules: unknown[], security_policies: unknown[], integrations: unknown[], performance_configs: unknown[], business_hours: Record<string, unknown>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneralSettings = { auto_save: boolean, language: string, timezone: string, date_format: string, currency: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SecuritySettings = { two_factor_enabled: boolean, session_timeout: number, password_min_length: number, password_require_special_chars: boolean, password_require_numbers: boolean, login_attempts_max: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationSettings = { push_notifications: boolean, email_notifications: boolean, sms_notifications: boolean, task_assignments: boolean, task_completions: boolean, system_alerts: boolean, daily_digest: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppearanceSettings = { dark_mode: boolean, primary_color: string, font_size: string, compact_view: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataManagementSettings = { auto_backup: boolean, backup_frequency: string, retention_days: number, export_format: string, compression_enabled: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DatabaseSettings = { connection_status: string, last_backup: string | null, database_size: string, connection_pool_size: number, query_timeout: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntegrationSettings = { api_enabled: boolean, webhook_url: string | null, external_services: Array<string>, sync_interval: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerformanceSettings = { cache_enabled: boolean, cache_size: number, max_concurrent_tasks: number, memory_limit: number, cpu_limit: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupSettings = { auto_backup: boolean, backup_location: string, encryption_enabled: boolean, compression_level: number, include_attachments: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticSettings = { logging_level: string, performance_monitoring: boolean, error_reporting: boolean, health_checks_enabled: boolean, metrics_collection: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemConfiguration = { database: DatabaseSettings, integrations: IntegrationSettings, performance: PerformanceSettings, backup: BackupSettings, diagnostics: DiagnosticSettings, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageSettings = { photo_storage_type: string, local_storage_path: string | null, cloud_provider: string | null, cloud_bucket: string | null, cloud_region: string | null, cloud_access_key: string | null, cloud_secret_key: string | null, auto_sync_photos: boolean, sync_on_wifi_only: boolean, max_photo_size_mb: number, compression_quality: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfileSettings = { full_name: string, email: string, phone: string | null, avatar_url: string | null, notes: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPreferences = { emailNotifications: boolean, pushNotifications: boolean, taskAssignments: boolean, taskUpdates: boolean, systemAlerts: boolean, weeklyReports: boolean, theme: string, language: string, dateFormat: string, timeFormat: string, highContrast: boolean, largeText: boolean, reduceMotion: boolean, screenReader: boolean, autoRefresh: boolean, refreshInterval: number, calendarView: string | null, calendarShowMyEventsOnly: boolean | null, calendarFilterStatuses: Array<string> | null, calendarFilterPriorities: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSecuritySettings = { two_factor_enabled: boolean, session_timeout: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPerformanceSettings = { cache_enabled: boolean, cache_size: number, offline_mode: boolean, sync_on_startup: boolean, background_sync: boolean, image_compression: boolean, preload_data: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAccessibilitySettings = { high_contrast: boolean, large_text: boolean, reduce_motion: boolean, screen_reader: boolean, focus_indicators: boolean, keyboard_navigation: boolean, text_to_speech: boolean, speech_rate: number, font_size: number, color_blind_mode: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserNotificationSettings = { email_enabled: boolean, push_enabled: boolean, in_app_enabled: boolean, task_assigned: boolean, task_updated: boolean, task_completed: boolean, task_overdue: boolean, system_alerts: boolean, maintenance: boolean, security_alerts: boolean, quiet_hours_enabled: boolean, quiet_hours_start: string, quiet_hours_end: string, digest_frequency: string, batch_notifications: boolean, sound_enabled: boolean, sound_volume: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSettings = { profile: UserProfileSettings, preferences: UserPreferences, security: UserSecuritySettings, performance: UserPerformanceSettings, accessibility: UserAccessibilitySettings, notifications: UserNotificationSettings, };


// @domain:organizations
// Organization types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Organization = { id: string, name: string, slug: string | null, legal_name: string | null, tax_id: string | null, siret: string | null, registration_number: string | null, email: string | null, phone: string | null, website: string | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, logo_url: string | null, logo_data: string | null, primary_color: string | null, secondary_color: string | null, accent_color: string | null, business_settings: string | null, invoice_settings: string | null, industry: string | null, company_size: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateOrganizationRequest = { name: string, slug: string | null, legal_name: string | null, tax_id: string | null, siret: string | null, registration_number: string | null, email: string | null, phone: string | null, website: string | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, industry: string | null, company_size: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateOrganizationRequest = { name: string | null, slug: string | null, legal_name: string | null, tax_id: string | null, siret: string | null, registration_number: string | null, email: string | null, phone: string | null, website: string | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, logo_url: string | null, logo_data: string | null, primary_color: string | null, secondary_color: string | null, accent_color: string | null, business_settings: string | null, invoice_settings: string | null, industry: string | null, company_size: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OnboardingStatus = { completed: boolean, current_step: number, has_organization: boolean, has_admin_user: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OnboardingData = { organization: CreateOrganizationRequest, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OrganizationSetting = { key: string, value: string, category: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateOrganizationSettingsRequest = { settings: { [key in string]?: string }, };



