// Auto-generated TypeScript types from Rust backend
// Do not edit manually - generated by export-types.rs

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

// JSON value helpers (mirrors Rust serde_json::Value)
export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

export type DeviceInfo = { device_type: string, os: string, browser: string | null, device_name: string | null, };


// Error types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Standard API response format
 */
export type ApiError = { message: string, code: string, details: JsonValue | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compressed API response for large payloads
 */
export type CompressedApiResponse = { success: boolean, compressed: boolean, data: string | null, error: ApiError | null, };


// Auth types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAccount = { id: string, email: string, username: string, first_name: string, last_name: string, role: UserRole, password_hash: string, salt: string | null, phone: string | null, is_active: boolean, last_login: bigint | null, login_count: number, preferences: string | null, synced: boolean, last_synced_at: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserRole = "admin" | "technician" | "supervisor" | "viewer";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSession = { id: string, user_id: string, username: string, email: string, role: UserRole, token: string, refresh_token: string | null, expires_at: string, last_activity: string, created_at: string, device_info: DeviceInfo | null, ip_address: string | null, user_agent: string | null, location: string | null, two_factor_verified: boolean, session_timeout_minutes: number | null, };


// Event types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventType = "meeting" | "appointment" | "task" | "reminder" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventParticipant = { id: string, name: string, email: string | null, status: ParticipantStatus, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParticipantStatus = "accepted" | "declined" | "tentative" | "needsaction";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventStatus = "confirmed" | "tentative" | "cancelled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateEventInput = { title: string, description: string | null, startDatetime: string, endDatetime: string, allDay: boolean | null, timezone: string | null, eventType: EventType | null, category: string | null, taskId: string | null, clientId: string | null, technicianId: string | null, location: string | null, meetingLink: string | null, isVirtual: boolean | null, participants: Array<EventParticipant> | null, reminders: Array<number> | null, color: string | null, tags: Array<string> | null, notes: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateEventInput = { title: string | null, description: string | null, startDatetime: string | null, endDatetime: string | null, allDay: boolean | null, timezone: string | null, eventType: EventType | null, category: string | null, taskId: string | null, clientId: string | null, location: string | null, meetingLink: string | null, isVirtual: boolean | null, participants: Array<EventParticipant> | null, status: EventStatus | null, reminders: Array<number> | null, color: string | null, tags: Array<string> | null, notes: string | null, };



// Calendar additional types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarEvent = { id: string, title: string, description: string | null, startDatetime: string, endDatetime: string, allDay: boolean, timezone: string, eventType: EventType, category: string | null, taskId: string | null, clientId: string | null, technicianId: string | null, location: string | null, meetingLink: string | null, isVirtual: boolean, participants: Array<EventParticipant>, isRecurring: boolean, recurrenceRule: string | null, parentEventId: string | null, reminders: Array<number>, status: EventStatus, color: string | null, tags: Array<string>, notes: string | null, synced: boolean, lastSyncedAt: bigint | null, createdAt: bigint, updatedAt: bigint, createdBy: string | null, updatedBy: string | null, deletedAt: bigint | null, deletedBy: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CalendarTask represents a task with calendar-specific information
 * Maps to the calendar_tasks SQL View
 */
export type CalendarTask = { id: string, task_number: string, title: string, status: TaskStatus, priority: TaskPriority, scheduled_date: string, start_time: string | null, end_time: string | null, vehicle_plate: string | null, vehicle_model: string | null, technician_id: string | null, technician_name: string | null, client_id: string | null, client_name: string | null, estimated_duration: number | null, actual_duration: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calendar filter for tasks
 */
export type CalendarFilter = { date_range: CalendarDateRange, technician_ids: Array<string> | null, statuses: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conflict detection result
 */
export type ConflictDetection = { has_conflict: boolean, conflict_type: string | null, conflicting_tasks: Array<CalendarTask>, message: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Date range filter for calendar queries
 */
export type CalendarDateRange = { start_date: string, end_date: string, };


// Client types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main Client entity
 */
export type Client = { id: string, name: string, email: string | null, phone: string | null, customer_type: CustomerType, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, total_tasks: number, active_tasks: number, completed_tasks: number, last_task_date: string | null, created_at: string, updated_at: string, created_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client with associated tasks
 */
export type ClientWithTasks = { id: string, name: string, email: string | null, phone: string | null, customer_type: CustomerType, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, total_tasks: number, active_tasks: number, completed_tasks: number, last_task_date: string | null, created_at: string, updated_at: string, created_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, tasks: Array<Task> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Conversion implementations for database operations
 * Client query parameters for listing and filtering
 */
export type ClientQuery = { page: number | null, limit: number | null, search: string | null, customer_type: CustomerType | null, sort_by: string | null, sort_order: SortOrder | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Customer type enumeration
 */
export type CustomerType = "individual" | "business";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Create client request
 */
export type CreateClientRequest = { name: string, email: string | null, phone: string | null, customer_type: CustomerType, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Update client request
 */
export type UpdateClientRequest = { id: string, name: string | null, email: string | null, phone: string | null, customer_type: CustomerType | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, company_name: string | null, contact_person: string | null, notes: string | null, tags: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client list response with pagination
 */
export type ClientListResponse = { data: Array<Client>, pagination: PaginationInfo, statistics: ClientStatistics | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client statistics
 */
export type ClientStatistics = { total_clients: bigint, individual_clients: bigint, business_clients: bigint, clients_with_tasks: bigint, new_clients_this_month: bigint, };


// Material types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material types for PPF workflows
 */
export type MaterialType = "ppf_film" | "adhesive" | "cleaning_solution" | "tool" | "consumable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unit of measure for materials
 */
export type UnitOfMeasure = "piece" | "meter" | "liter" | "gram" | "roll";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material inventory item
 */
export type Material = { id: string, sku: string, name: string, description: string | null, material_type: MaterialType, category: string | null, subcategory: string | null, category_id: string | null, brand: string | null, model: string | null, specifications: JsonValue, unit_of_measure: UnitOfMeasure, current_stock: number, minimum_stock: number | null, maximum_stock: number | null, reorder_point: number | null, unit_cost: number | null, currency: string, supplier_id: string | null, supplier_name: string | null, supplier_sku: string | null, quality_grade: string | null, certification: string | null, expiry_date: string | null, batch_number: string | null, serial_numbers: Array<string> | null, is_active: boolean, is_discontinued: boolean, storage_location: string | null, warehouse_id: string | null, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material consumption record for interventions
 */
export type MaterialConsumption = { id: string, intervention_id: string, material_id: string, step_id: string | null, quantity_used: number, unit_cost: number | null, total_cost: number | null, waste_quantity: number, waste_reason: string | null, batch_used: string | null, expiry_used: string | null, quality_notes: string | null, step_number: number | null, recorded_by: string | null, recorded_at: string, created_at: string, updated_at: string, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material inventory statistics
 */
export type MaterialStats = { total_materials: number, active_materials: number, low_stock_materials: number, expired_materials: number, total_value: number, materials_by_type: { [key in string]?: number }, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Enhanced inventory statistics
 */
export type InventoryStats = { total_materials: number, active_materials: number, low_stock_materials: number, expired_materials: number, total_value: number, materials_by_category: { [key in string]?: number }, recent_transactions: Array<InventoryTransaction>, stock_turnover_rate: number, average_inventory_age: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inventory transaction record
 */
export type InventoryTransaction = { id: string, material_id: string, transaction_type: InventoryTransactionType, quantity: number, previous_stock: number, new_stock: number, reference_number: string | null, reference_type: string | null, notes: string | null, unit_cost: number | null, total_cost: number | null, warehouse_id: string | null, location_from: string | null, location_to: string | null, batch_number: string | null, expiry_date: string | null, quality_status: string | null, intervention_id: string | null, step_id: string | null, performed_by: string, performed_at: string, created_at: string, updated_at: string, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transaction types for inventory movements
 */
export type InventoryTransactionType = "stock_in" | "stock_out" | "adjustment" | "transfer" | "waste" | "return";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supplier information
 */
export type Supplier = { id: string, name: string, code: string | null, contact_person: string | null, email: string | null, phone: string | null, website: string | null, address_street: string | null, address_city: string | null, address_state: string | null, address_zip: string | null, address_country: string | null, tax_id: string | null, business_license: string | null, payment_terms: string | null, lead_time_days: number, is_active: boolean, is_preferred: boolean, quality_rating: number | null, delivery_rating: number | null, on_time_delivery_rate: number | null, notes: string | null, special_instructions: string | null, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material category for hierarchical organization
 */
export type MaterialCategory = { id: string, name: string, code: string | null, parent_id: string | null, level: number, description: string | null, color: string | null, is_active: boolean, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material consumption summary for an intervention
 */
export type InterventionMaterialSummary = { intervention_id: string, total_materials_used: number, total_cost: number, materials: Array<MaterialConsumptionSummary>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Summary of material consumption
 */
export type MaterialConsumptionSummary = { material_id: string, material_name: string, material_type: string, quantity_used: number, unit_cost: number | null, total_cost: number | null, waste_quantity: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inventory movement summary
 */
export type InventoryMovementSummary = { material_id: string, material_name: string, total_stock_in: number, total_stock_out: number, net_movement: number, current_stock: number, last_transaction_date: string | null, };


// Task types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main Task entity
 */
export type Task = { id: string, task_number: string, title: string, description: string | null, vehicle_plate: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_make: string | null, vin: string | null, ppf_zones: Array<string> | null, custom_ppf_zones: Array<string> | null, status: TaskStatus, priority: TaskPriority, technician_id: string | null, assigned_at: string | null, assigned_by: string | null, scheduled_date: string | null, start_time: string | null, end_time: string | null, date_rdv: string | null, heure_rdv: string | null, template_id: string | null, workflow_id: string | null, workflow_status: string | null, current_workflow_step_id: string | null, started_at: string | null, completed_at: string | null, completed_steps: string | null, client_id: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, external_id: string | null, lot_film: string | null, checklist_completed: boolean, notes: string | null, tags: string | null, estimated_duration: number | null, actual_duration: number | null, created_at: string, updated_at: string, creator_id: string | null, created_by: string | null, updated_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task status enumeration
 */
export type TaskStatus = "draft" | "scheduled" | "in_progress" | "completed" | "cancelled" | "on_hold" | "pending" | "invalid" | "archived" | "failed" | "overdue" | "assigned" | "paused";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task priority enumeration
 */
export type TaskPriority = "low" | "medium" | "high" | "urgent";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task history entry - tracks status changes
 */
export type TaskHistory = { id: string, task_id: string, old_status: string | null, new_status: string, reason: string | null, changed_at: bigint, changed_by: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Assignment status for task assignment validation
 */
export type AssignmentStatus = "assigned" | "available" | "restricted" | "unavailable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Availability status for task availability checks
 */
export type AvailabilityStatus = "available" | "unavailable" | "locked" | "scheduled_conflict" | "material_unavailable";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for task assignment check
 */
export type AssignmentCheckResponse = { task_id: string, user_id: string, status: AssignmentStatus, reason: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for task availability check
 */
export type AvailabilityCheckResponse = { task_id: string, status: AvailabilityStatus, reason: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for creating a new task
 */
export type CreateTaskRequest = { vehicle_plate: string, vehicle_model: string, ppf_zones: Array<string>, scheduled_date: string, external_id: string | null, status: TaskStatus | null, technician_id: string | null, start_time: string | null, end_time: string | null, checklist_completed: boolean | null, notes: string | null, title: string | null, vehicle_make: string | null, vehicle_year: string | null, vin: string | null, date_rdv: string | null, heure_rdv: string | null, lot_film: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, custom_ppf_zones: Array<string> | null, template_id: string | null, workflow_id: string | null, task_number: string | null, creator_id: string | null, created_by: string | null, description: string | null, priority: TaskPriority | null, client_id: string | null, estimated_duration: number | null, tags: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for updating a task
 */
export type UpdateTaskRequest = { id: string | null, title: string | null, description: string | null, priority: TaskPriority | null, status: TaskStatus | null, vehicle_plate: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_make: string | null, vin: string | null, ppf_zones: Array<string> | null, custom_ppf_zones: Array<string> | null, client_id: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, external_id: string | null, lot_film: string | null, checklist_completed: boolean | null, scheduled_date: string | null, start_time: string | null, end_time: string | null, date_rdv: string | null, heure_rdv: string | null, template_id: string | null, workflow_id: string | null, estimated_duration: number | null, notes: string | null, tags: string | null, technician_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Query parameters for task listing
 */
export type TaskQuery = { page: number | null, limit: number | null, status: TaskStatus | null, technician_id: string | null, client_id: string | null, priority: TaskPriority | null, search: string | null, from_date: string | null, to_date: string | null, sort_by: string, sort_order: SortOrder, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task photo information
 */
export type TaskPhoto = { id: string, task_id: string, photo_type: string, file_path: string, file_size: bigint, mime_type: string, url: string, description: string | null, taken_at: bigint | null, created_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sort order for queries
 */
export type SortOrder = "asc" | "desc";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task with full details including related data
 */
export type TaskWithDetails = { id: string, task_number: string, title: string, description: string | null, vehicle_plate: string | null, vehicle_model: string | null, vehicle_year: string | null, vehicle_make: string | null, vin: string | null, ppf_zones: Array<string> | null, custom_ppf_zones: Array<string> | null, status: TaskStatus, priority: TaskPriority, technician_id: string | null, assigned_at: string | null, assigned_by: string | null, scheduled_date: string | null, start_time: string | null, end_time: string | null, date_rdv: string | null, heure_rdv: string | null, template_id: string | null, workflow_id: string | null, workflow_status: string | null, current_workflow_step_id: string | null, started_at: string | null, completed_at: string | null, completed_steps: string | null, client_id: string | null, customer_name: string | null, customer_email: string | null, customer_phone: string | null, customer_address: string | null, external_id: string | null, lot_film: string | null, checklist_completed: boolean, notes: string | null, tags: string | null, estimated_duration: number | null, actual_duration: number | null, created_at: string, updated_at: string, creator_id: string | null, created_by: string | null, updated_by: string | null, deleted_at: string | null, deleted_by: string | null, synced: boolean, last_synced_at: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for deleting a task
 */
export type DeleteTaskRequest = { id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for task listing with pagination
 */
export type TaskListResponse = { data: Array<TaskWithDetails>, pagination: PaginationInfo, statistics: TaskStatistics | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Pagination information
 */
export type PaginationInfo = { page: number, limit: number, total: bigint, total_pages: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task statistics
 */
export type TaskStatistics = { total_tasks: number, draft_tasks: number, scheduled_tasks: number, in_progress_tasks: number, completed_tasks: number, cancelled_tasks: number, on_hold_tasks: number, pending_tasks: number, invalid_tasks: number, archived_tasks: number, failed_tasks: number, overdue_tasks: number, assigned_tasks: number, paused_tasks: number, };


// Repository types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Paginated result
 */
export type PaginatedResult<T> = { data: Array<T>, pagination: PaginationInfo, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cache statistics
 */
export type CacheStats = { size: number, };


// Photo types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Photo = { id: string, intervention_id: string, step_id: string | null, step_number: number | null, file_path: string, file_name: string | null, file_size: bigint | null, mime_type: string, width: number | null, height: number | null, photo_type: PhotoType | null, photo_category: PhotoCategory | null, photo_angle: string | null, zone: string | null, title: string | null, description: string | null, notes: string | null, annotations: JsonValue, gps_location_lat: number | null, gps_location_lon: number | null, gps_location_accuracy: number | null, quality_score: number | null, blur_score: number | null, exposure_score: number | null, composition_score: number | null, is_required: boolean, is_approved: boolean, approved_by: string | null, approved_at: bigint | null, rejection_reason: string | null, synced: boolean, storage_url: string | null, upload_retry_count: number, upload_error: string | null, last_synced_at: bigint | null, captured_at: bigint | null, uploaded_at: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhotoType = "before" | "during" | "after";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhotoCategory = "vehicle_condition" | "workspace" | "step_progress" | "qc_check" | "final_result" | "other";


// Intervention types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main intervention struct
 */
export type Intervention = { id: string, task_id: string, task_number: string | null, status: InterventionStatus, vehicle_plate: string, vehicle_model: string | null, vehicle_make: string | null, vehicle_year: number | null, vehicle_color: string | null, vehicle_vin: string | null, client_id: string | null, client_name: string | null, client_email: string | null, client_phone: string | null, technician_id: string | null, technician_name: string | null, intervention_type: InterventionType, 
/**
 * Number of completed steps (0-based count, not array index)
 */
current_step: number, completion_percentage: number, ppf_zones_config: Array<string> | null, ppf_zones_extended: JsonValue, film_type: FilmType | null, film_brand: string | null, film_model: string | null, scheduled_at: TimestampString, started_at: TimestampString, completed_at: TimestampString, paused_at: TimestampString, estimated_duration: number | null, actual_duration: number | null, weather_condition: WeatherCondition | null, lighting_condition: LightingCondition | null, work_location: WorkLocation | null, temperature_celsius: number | null, humidity_percentage: number | null, start_location_lat: number | null, start_location_lon: number | null, start_location_accuracy: number | null, end_location_lat: number | null, end_location_lon: number | null, end_location_accuracy: number | null, customer_satisfaction: number | null, quality_score: number | null, final_observations: Array<string> | null, customer_signature: string | null, customer_comments: string | null, metadata: JsonValue, notes: string | null, special_instructions: string | null, device_info: JsonValue, app_version: string | null, synced: boolean, last_synced_at: bigint | null, sync_error: string | null, created_at: bigint, updated_at: bigint, created_by: string | null, updated_by: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention status enum
 */
export type InterventionStatus = "pending" | "in_progress" | "paused" | "completed" | "cancelled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention type
 */
export type InterventionType = "ppf" | "ceramic" | "detailing" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Filter for intervention queries
 */
export type InterventionFilter = { task_id: string | null, status: string | null, technician_id: string | null, client_id: string | null, priority: string | null, from_date: string | null, to_date: string | null, intervention_type: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for bulk updating interventions
 */
export type BulkUpdateInterventionRequest = { intervention_ids: Array<string>, status: string | null, technician_id: string | null, priority: string | null, updates: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GPS coordinates
 */
export type GpsLocation = { latitude: number, longitude: number, accuracy: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Film type for PPF
 */
export type FilmType = "standard" | "premium" | "matte" | "colored";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Weather conditions for intervention
 */
export type WeatherCondition = "sunny" | "cloudy" | "rainy" | "foggy" | "windy" | "other";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lighting conditions
 */
export type LightingCondition = "natural" | "artificial" | "mixed";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Work location type
 */
export type WorkLocation = "indoor" | "outdoor" | "semi_covered";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wrapper type for timestamps that serializes to ISO string
 */
export type TimestampString = bigint | null;

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * GPS coordinates for location tracking
 */
export type GpsCoordinates = { latitude: number, longitude: number, accuracy: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention step struct
 */
export type InterventionStep = { id: string, intervention_id: string, step_number: number, step_name: string, step_type: StepType, step_status: StepStatus, description: string | null, instructions: JsonValue, quality_checkpoints: Array<string> | null, is_mandatory: boolean, requires_photos: boolean, min_photos_required: number, max_photos_allowed: number, started_at: TimestampString, completed_at: TimestampString, paused_at: TimestampString, duration_seconds: number | null, estimated_duration_seconds: number | null, step_data: JsonValue, collected_data: JsonValue, measurements: JsonValue, observations: Array<string> | null, photo_count: number, required_photos_completed: boolean, photo_urls: Array<string> | null, validation_data: JsonValue, validation_errors: Array<string> | null, validation_score: number | null, requires_supervisor_approval: boolean, approved_by: string | null, approved_at: TimestampString, rejection_reason: string | null, location_lat: number | null, location_lon: number | null, location_accuracy: number | null, device_timestamp: TimestampString, server_timestamp: TimestampString, title: string | null, notes: string | null, synced: boolean, last_synced_at: TimestampString, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step type enum
 */
export type StepType = "inspection" | "preparation" | "installation" | "finalization";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to start a new intervention
 */
export type StartInterventionRequest = { task_id: string, intervention_number: string | null, ppf_zones: Array<string>, custom_zones: Array<string> | null, film_type: string, film_brand: string | null, film_model: string | null, weather_condition: string, lighting_condition: string, work_location: string, temperature: number | null, humidity: number | null, technician_id: string, assistant_ids: Array<string> | null, scheduled_start: string, estimated_duration: number, gps_coordinates: GpsCoordinates | null, address: string | null, notes: string | null, customer_requirements: Array<string> | null, special_instructions: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to advance a step
 */
export type AdvanceStepRequest = { intervention_id: string, step_id: string, collected_data: JsonValue, photos: Array<string> | null, notes: string | null, quality_check_passed: boolean, issues: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request for saving step progress without advancing
 */
export type SaveStepProgressRequest = { step_id: string, collected_data: JsonValue, notes: string | null, photos: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to finalize an intervention
 */
export type FinalizeInterventionRequest = { intervention_id: string, collected_data: JsonValue, photos: Array<string> | null, customer_satisfaction: number | null, quality_score: number | null, final_observations: Array<string> | null, customer_signature: string | null, customer_comments: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for starting an intervention
 */
export type StartInterventionResponse = { intervention: Intervention, steps: Array<InterventionStep>, initial_requirements: Array<StepRequirement>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for advancing a step
 */
export type AdvanceStepResponse = { step: InterventionStep, next_step: InterventionStep | null, progress_percentage: number, requirements_completed: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for saving step progress
 */
export type SaveStepProgressResponse = { step: InterventionStep, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response for finalizing an intervention
 */
export type FinalizeInterventionResponse = { intervention: Intervention, metrics: InterventionMetrics, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step requirement for workflow validation
 */
export type StepRequirement = { step_id: string, requirement_type: string, description: string, is_mandatory: boolean, is_completed: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention step with associated photos
 */
export type InterventionStepWithPhotos = { step: InterventionStep, photos: Array<Photo>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention with all related data
 */
export type InterventionWithDetails = { intervention: Intervention, steps: Array<InterventionStepWithPhotos>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress tracking for interventions
 */
export type InterventionProgress = { intervention_id: string, current_step: number, total_steps: number, completed_steps: number, completion_percentage: number, estimated_time_remaining: number | null, status: InterventionStatus, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention metrics for finalization
 */
export type InterventionMetrics = { total_duration_minutes: number, completion_rate: number, quality_score: number | null, customer_satisfaction: number | null, steps_completed: number, total_steps: number, photos_taken: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step status enum
 */
export type StepStatus = "pending" | "in_progress" | "paused" | "completed" | "failed" | "skipped" | "rework";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationChannel = "Email" | "Sms" | "Push";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationType = "TaskAssignment" | "TaskUpdate" | "TaskCompletion" | "StatusChange" | "OverdueWarning" | "SystemAlert" | "NewAssignment" | "DeadlineReminder" | "QualityApproval";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationTemplate = { id: string, name: string, notification_type: NotificationType, channel: NotificationChannel, subject_template: string, body_template: string, variables: Array<string>, is_active: boolean, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationMessage = { id: string, user_id: string, notification_type: NotificationType, channel: NotificationChannel, recipient: string, subject: string | null, body: string, priority: NotificationPriority, status: NotificationStatus, scheduled_at: string, sent_at: string, error_message: string | null, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationPriority = "Low" | "Normal" | "High" | "Critical";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationStatus = "Pending" | "Sent" | "Failed" | "Cancelled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TemplateVariables = { user_name: string | null, task_title: string | null, task_id: string | null, client_name: string | null, due_date: string | null, status: string | null, priority: string | null, assignee_name: string | null, system_message: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmailProvider = "SendGrid" | "Mailgun" | "Smtp";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EmailConfig = { provider: EmailProvider, api_key: string, from_email: string, from_name: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmsProvider = "Twilio" | "AwsSns";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SmsConfig = { provider: SmsProvider, api_key: string, from_number: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationConfig = { email: EmailConfig | null, sms: SmsConfig | null, push_enabled: boolean, quiet_hours_start: string | null, quiet_hours_end: string | null, timezone: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateNotificationConfigRequest = { email_provider: string | null, email_api_key: string | null, email_from_email: string | null, email_from_name: string | null, sms_provider: string | null, sms_api_key: string | null, sms_from_number: string | null, push_enabled: boolean | null, quiet_hours_start: string | null, quiet_hours_end: string | null, timezone: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SendNotificationRequest = { user_id: string, notification_type: NotificationType, recipient: string, variables: TemplateVariables, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message entity representing a single message
 */
export type Message = { id: string, message_type: string, sender_id: string | null, recipient_id: string | null, recipient_email: string | null, recipient_phone: string | null, subject: string | null, body: string, template_id: string | null, task_id: string | null, client_id: string | null, status: string, priority: string, scheduled_at: bigint | null, sent_at: bigint | null, read_at: bigint | null, error_message: string | null, metadata: string | null, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message types supported by the system
 */
export type MessageType = "Email" | "Sms" | "InApp";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message status enumeration
 */
export type MessageStatus = "Pending" | "Sent" | "Delivered" | "Failed" | "Read";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message priority levels
 */
export type MessagePriority = "Low" | "Normal" | "High" | "Urgent";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message query filters
 */
export type MessageQuery = { message_type: string | null, sender_id: string | null, recipient_id: string | null, task_id: string | null, client_id: string | null, status: string | null, priority: string | null, date_from: bigint | null, date_to: bigint | null, limit: number | null, offset: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message list response
 */
export type MessageListResponse = { messages: Array<Message>, total: number, has_more: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Message template for reusable messages
 */
export type MessageTemplate = { id: string, name: string, description: string | null, message_type: string, subject: string | null, body: string, variables: string | null, category: string, is_active: boolean, created_by: string | null, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to create/update a message template
 */
export type MessageTemplateRequest = { name: string, description: string | null, message_type: string, subject: string | null, body: string, variables: Array<string> | null, category: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to send a new message
 */
export type SendMessageRequest = { message_type: string, recipient_id: string | null, recipient_email: string | null, recipient_phone: string | null, subject: string | null, body: string, template_id: string | null, task_id: string | null, client_id: string | null, priority: string | null, scheduled_at: bigint | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User notification preferences
 */
export type NotificationPreferences = { id: string, user_id: string, email_enabled: boolean, sms_enabled: boolean, in_app_enabled: boolean, task_assigned: boolean, task_updated: boolean, task_completed: boolean, task_overdue: boolean, client_created: boolean, client_updated: boolean, system_alerts: boolean, maintenance_notifications: boolean, quiet_hours_enabled: boolean, quiet_hours_start: string | null, quiet_hours_end: string | null, email_frequency: string, email_digest_time: string, created_at: bigint, updated_at: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Request to update notification preferences
 */
export type UpdateNotificationPreferencesRequest = { email_enabled: boolean | null, sms_enabled: boolean | null, in_app_enabled: boolean | null, task_assigned: boolean | null, task_updated: boolean | null, task_completed: boolean | null, task_overdue: boolean | null, client_created: boolean | null, client_updated: boolean | null, system_alerts: boolean | null, maintenance_notifications: boolean | null, quiet_hours_enabled: boolean | null, quiet_hours_start: string | null, quiet_hours_end: string | null, email_frequency: string | null, email_digest_time: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateUserRequest = { email: string, first_name: string, last_name: string, role: string, password: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateUserRequest = { email: string | null, first_name: string | null, last_name: string | null, role: string | null, is_active: boolean | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User action types for CRUD operations
 */
export type UserAction = { "action": "Create", data: CreateUserRequest, } | { "action": "Get", id: string, } | { "action": "Update", id: string, data: UpdateUserRequest, } | { "action": "Delete", id: string, } | { "action": "List", limit: number | null, offset: number | null, } | { "action": "ChangePassword", id: string, new_password: string, } | { "action": "ChangeRole", id: string, new_role: UserRole, } | { "action": "Ban", id: string, } | { "action": "Unban", id: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * User list response
 */
export type UserListResponse = { data: Array<UserAccount>, };


// Status types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatusDistribution = { quote: number, scheduled: number, in_progress: number, paused: number, completed: number, cancelled: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StatusTransitionRequest = { task_id: string, new_status: string, reason: string | null, };


// Sync types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entity types that can be synchronized
 */
export type EntityType = "task" | "client" | "intervention" | "step" | "photo" | "user";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Main sync operation structure
 */
export type SyncOperation = { id: bigint | null, operation_type: OperationType, entity_type: EntityType, entity_id: string, data: JsonValue, dependencies: Array<string>, timestamp_utc: string, retry_count: number, max_retries: number, last_error: string | null, status: SyncStatus, created_at: string, updated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sync operation status
 */
export type SyncStatus = "pending" | "processing" | "completed" | "failed" | "abandoned";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operation types for sync queue
 */
export type OperationType = "create" | "update" | "delete";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metrics for sync queue monitoring
 */
export type SyncQueueMetrics = { pending_operations: bigint, processing_operations: bigint, completed_operations: bigint, failed_operations: bigint, abandoned_operations: bigint, oldest_pending_age_seconds: bigint | null, average_retry_count: number, };


// Reports types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Date range for reports
 */
export type DateRange = { start: string, end: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report filters
 */
export type ReportFilters = { technician_ids: Array<string> | null, client_ids: Array<string> | null, statuses: Array<string> | null, priorities: Array<string> | null, ppf_zones: Array<string> | null, vehicle_models: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report types enumeration
 */
export type ReportType = "overview" | "data_explorer" | "tasks" | "technicians" | "clients" | "quality" | "materials" | "geographic" | "seasonal" | "operational_intelligence";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Export formats
 */
export type ExportFormat = "pdf" | "csv" | "excel";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report metadata information
 */
export type ReportMetadata = { title: string, date_range: DateRange, generated_at: string, filters: ReportFilters, total_records: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search result for data explorer
 */
export type SearchResult = { id: string, entity_type: EntityType, title: string, subtitle: string, status: string | null, date: string | null, metadata: { [key in string]?: string }, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search results across multiple entities
 */
export type SearchResults = { tasks: Array<Task>, clients: Array<Client>, interventions: Array<Intervention>, total_results: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search filters for data explorer
 */
export type SearchFilters = { technician_ids: Array<string> | null, client_ids: Array<string> | null, statuses: Array<string> | null, priorities: Array<string> | null, ppf_zones: Array<string> | null, vehicle_models: Array<string> | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Search response
 */
export type SearchResponse = { results: Array<SearchResult>, total_count: bigint, has_more: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Entity counts for Data Explorer
 */
export type EntityCounts = { tasks: bigint, clients: bigint, interventions: bigint, technicians: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics KPI categories
 */
export type KpiCategory = "operational" | "financial" | "quality" | "efficiency" | "client_satisfaction";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * KPI trend direction
 */
export type TrendDirection = "up" | "down" | "stable" | "unknown";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Calculation period
 */
export type CalculationPeriod = "hourly" | "daily" | "weekly" | "monthly";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics KPI definition and current value
 */
export type AnalyticsKpi = { id: string, kpi_name: string, kpi_category: KpiCategory, display_name: string, description: string | null, unit: string | null, calculation_method: string, current_value: number | null, previous_value: number | null, target_value: number | null, trend_direction: TrendDirection | null, last_calculated: string, calculation_period: CalculationPeriod, is_active: boolean, priority: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Metric value types
 */
export type MetricValueType = "count" | "percentage" | "currency" | "duration" | "rating";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics metric data point
 */
export type AnalyticsMetric = { id: string, metric_name: string, metric_category: string, value: number, value_type: MetricValueType, dimensions: string | null, timestamp: string, period_start: string, period_end: string, source: string, source_id: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dashboard types
 */
export type DashboardType = "main" | "operational" | "financial" | "quality" | "custom";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dashboard configuration
 */
export type AnalyticsDashboard = { id: string, name: string, dashboard_type: DashboardType, layout_config: string | null, widget_configs: string | null, filters_config: string | null, user_id: string | null, is_public: boolean, is_default: boolean, is_active: boolean, created_at: string, updated_at: string, created_by: string | null, updated_by: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chart data point for frontend visualization
 */
export type ChartDataPoint = { label: string, value: number, category: string | null, timestamp: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chart configuration for dashboard widgets
 */
export type ChartConfig = { chart_type: string, title: string, x_axis_label: string | null, y_axis_label: string | null, data: Array<ChartDataPoint>, colors: Array<string> | null, show_legend: boolean, show_grid: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dashboard widget types
 */
export type WidgetType = "kpi_card" | "chart" | "table" | "metric_grid" | "trend_indicator";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Dashboard widget configuration
 */
export type DashboardWidget = { id: string, widget_type: WidgetType, title: string, kpi_id: string | null, chart_config: ChartConfig | null, metric_names: Array<string> | null, position: WidgetPosition, size: WidgetSize, refresh_interval: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Widget position on dashboard grid
 */
export type WidgetPosition = { x: number, y: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Widget size on dashboard grid
 */
export type WidgetSize = { width: number, height: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics dashboard data response
 */
export type AnalyticsDashboardData = { dashboard: AnalyticsDashboard, kpis: Array<AnalyticsKpi>, widgets: Array<DashboardWidget>, date_range: DateRange, last_updated: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics time series data for trend charts
 */
export type AnalyticsTimeSeries = { metric_name: string, data_points: Array<ChartDataPoint>, period: string, aggregation: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Analytics summary for quick overview
 */
export type AnalyticsSummary = { total_interventions: bigint, completed_today: bigint, active_technicians: bigint, average_completion_time: number, client_satisfaction_score: number, quality_compliance_rate: number, revenue_this_month: number, inventory_turnover: number, top_performing_technician: string | null, most_common_issue: string | null, last_updated: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Overview report combining all individual reports
 */
export type OverviewReport = { task_completion: TaskCompletionReport, technician_performance: TechnicianPerformanceReport, client_analytics: ClientAnalyticsReport, quality_compliance: QualityComplianceReport, material_usage: MaterialUsageReport, geographic: GeographicReport, seasonal: SeasonalReport, operational_intelligence: OperationalIntelligenceReport, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Geographic analytics report
 */
export type GeographicReport = { metadata: ReportMetadata, heat_map_data: Array<HeatMapPoint>, service_areas: Array<ServiceArea>, geographic_stats: GeographicStats, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Seasonal trend analysis report
 */
export type SeasonalReport = { metadata: ReportMetadata, seasonal_patterns: Array<SeasonalPattern>, weather_correlation: WeatherCorrelation, peak_periods: Array<PeakPeriod>, performance_trends: Array<PerformanceTrend>, completion_predictions: Array<CompletionTimePrediction>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Heat map point for geographic visualization
 */
export type HeatMapPoint = { latitude: number, longitude: number, intensity: number, intervention_count: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Geographic statistics
 */
export type GeographicStats = { total_points: number, unique_locations: number, average_cluster_density: number, coverage_area_km2: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Service area analysis
 */
export type ServiceArea = { center_lat: number, center_lon: number, coverage_radius_km: number, intervention_count: number, unique_clients: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Peak period identification
 */
export type PeakPeriod = { period_type: string, period_value: string, task_volume: bigint, average_completion_time: number, resource_utilization: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Seasonal pattern analysis
 */
export type SeasonalPattern = { season: string, month: number, average_tasks_per_day: number, completion_rate: number, average_duration_minutes: number, common_issue_types: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Weather correlation analysis
 */
export type WeatherCorrelation = { temperature_impact: number, precipitation_impact: number, wind_impact: number, seasonal_adjustment_factor: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task completion report
 */
export type TaskCompletionReport = { metadata: ReportMetadata, summary: TaskCompletionSummary, daily_breakdown: Array<DailyTaskData>, status_distribution: Array<StatusCount>, technician_breakdown: Array<TechnicianTaskData>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Task completion summary
 */
export type TaskCompletionSummary = { total_tasks: bigint, completed_tasks: bigint, completion_rate: number, average_duration: number | null, on_time_completion_rate: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Daily task data
 */
export type DailyTaskData = { date: string, total: bigint, completed: bigint, in_progress: bigint, pending: bigint, cancelled: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Status count
 */
export type StatusCount = { status: string, count: bigint, percentage: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Technician task data
 */
export type TechnicianTaskData = { technician_id: string, technician_name: string, tasks_completed: bigint, average_time_per_task: number | null, quality_score: number | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Technician performance report
 */
export type TechnicianPerformanceReport = { metadata: ReportMetadata, technicians: Array<TechnicianPerformance>, benchmarks: PerformanceBenchmarks, trends: Array<PerformanceTrend>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual technician performance
 */
export type TechnicianPerformance = { id: string, name: string, metrics: TechnicianMetrics, trends: Array<PerformanceTrend>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Technician metrics
 */
export type TechnicianMetrics = { tasks_completed: bigint, average_time_per_task: number, quality_score: number, customer_satisfaction: number, utilization_rate: number, efficiency_score: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Performance benchmarks
 */
export type PerformanceBenchmarks = { top_performer_score: number, team_average: number, industry_average: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Performance trend data
 */
export type PerformanceTrend = { period: string, performance_score: number, tasks_completed: bigint, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client analytics report
 */
export type ClientAnalyticsReport = { metadata: ReportMetadata, summary: ClientSummary, retention_analysis: RetentionAnalysis, revenue_analysis: RevenueAnalysis, top_clients: Array<ClientPerformance>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client summary
 */
export type ClientSummary = { total_clients: bigint, new_clients_this_period: bigint, returning_clients: bigint, retention_rate: number, average_revenue_per_client: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Retention analysis
 */
export type RetentionAnalysis = { new_client_rate: number, repeat_client_rate: number, churn_rate: number, lifetime_value: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Revenue analysis
 */
export type RevenueAnalysis = { total_revenue: number, revenue_by_client_type: { [key in string]?: number }, average_revenue_per_task: number, revenue_growth_rate: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Client performance data
 */
export type ClientPerformance = { id: string, name: string, customer_type: string, total_revenue: number, tasks_completed: bigint, average_revenue_per_task: number, satisfaction_score: number | null, retention_status: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality compliance report
 */
export type QualityComplianceReport = { metadata: ReportMetadata, summary: QualitySummary, quality_trends: Array<QualityTrend>, common_issues: Array<QualityIssue>, compliance_metrics: ComplianceMetrics, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality summary
 */
export type QualitySummary = { overall_quality_score: number, photo_compliance_rate: number, step_completion_accuracy: number, defect_rate: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality trend data
 */
export type QualityTrend = { date: string, quality_score: number, photo_compliance: number, step_accuracy: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Quality issue
 */
export type QualityIssue = { issue_type: string, count: bigint, percentage: number, severity: string, recommended_action: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Compliance metrics
 */
export type ComplianceMetrics = { documentation_completeness: number, photo_quality_score: number, workflow_adherence: number, safety_compliance: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material usage report
 */
export type MaterialUsageReport = { metadata: ReportMetadata, summary: MaterialSummary, consumption_breakdown: Array<ReportMaterialConsumption>, cost_analysis: MaterialCostAnalysis, efficiency_metrics: MaterialEfficiency, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material summary
 */
export type MaterialSummary = { total_material_cost: number, cost_per_task: number, waste_percentage: number, inventory_turnover: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material consumption data for reports
 */
export type ReportMaterialConsumption = { material_id: string, material_name: string, material_type: string, quantity_used: number, unit_cost: number, total_cost: number, waste_quantity: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material cost analysis
 */
export type MaterialCostAnalysis = { cost_by_material_type: { [key in string]?: number }, cost_trends: Array<CostTrend>, supplier_performance: Array<SupplierPerformance>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cost trend data
 */
export type CostTrend = { period: string, material_cost: number, cost_per_task: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supplier performance
 */
export type SupplierPerformance = { supplier_name: string, material_type: string, total_cost: number, quality_score: number, delivery_reliability: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Material efficiency metrics
 */
export type MaterialEfficiency = { utilization_rate: number, waste_reduction_rate: number, cost_efficiency_score: number, inventory_optimization: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Export result
 */
export type ExportResult = { download_url: string | null, content: string | null, file_name: string, file_size: bigint, format: ExportFormat, expires_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report generation request
 */
export type ReportRequest = { report_type: ReportType, date_range: DateRange, filters: ReportFilters, format: ExportFormat | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report generation response
 */
export type ReportResponse = { report_id: string, status: ReportStatus, progress: number, estimated_completion: string, result: ExportResult | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Report generation status
 */
export type ReportStatus = "pending" | "processing" | "completed" | "failed" | "cancelled";

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Operational intelligence report
 */
export type OperationalIntelligenceReport = { metadata: ReportMetadata, step_bottlenecks: Array<StepBottleneck>, intervention_bottlenecks: Array<InterventionBottleneck>, resource_utilization: Array<ResourceUtilization>, process_efficiency: ProcessEfficiencyMetrics, recommendations: Array<WorkflowRecommendation>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Step bottleneck analysis
 */
export type StepBottleneck = { step_number: number, step_name: string, step_type: string, average_duration_minutes: number, median_duration_minutes: number, max_duration_minutes: number, failure_rate: number, rework_rate: number, pause_rate: number, total_occurrences: bigint, bottleneck_severity: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Intervention bottleneck analysis
 */
export type InterventionBottleneck = { intervention_id: string, task_number: string, technician_name: string, vehicle_plate: string, stuck_at_step: number, time_at_current_step_hours: number, total_duration_hours: number, estimated_vs_actual_ratio: number, priority: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Individual intervention report result
 */
export type InterventionReportResult = { success: boolean, download_url: string | null, file_path: string | null, file_name: string | null, format: string, file_size: bigint | null, generated_at: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Resource utilization metrics
 */
export type ResourceUtilization = { technician_id: string, technician_name: string, active_interventions: bigint, completed_today: bigint, average_completion_time_hours: number, utilization_percentage: number, workload_distribution: Array<WorkloadPeriod>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Process efficiency metrics
 */
export type ProcessEfficiencyMetrics = { overall_efficiency_score: number, average_step_completion_time: number, step_success_rate: number, rework_percentage: number, resource_utilization_rate: number, bottleneck_impact_score: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workflow optimization recommendations
 */
export type WorkflowRecommendation = { recommendation_type: string, priority: string, description: string, impact_score: number, implementation_effort: string, affected_steps: Array<number>, affected_technicians: Array<string>, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Completion time prediction result
 */
export type CompletionTimePrediction = { predicted_duration_minutes: number, confidence_interval: [number, number], factors_influencing: Array<string>, historical_average: number, prediction_accuracy: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Workload period breakdown
 */
export type WorkloadPeriod = { period: string, interventions_count: bigint, average_duration_hours: number, };


// Settings types
// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppSettings = { general: GeneralSettings, security: SecuritySettings, notifications: NotificationSettings, appearance: AppearanceSettings, data_management: DataManagementSettings, storage: StorageSettings, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GeneralSettings = { auto_save: boolean, language: string, timezone: string, date_format: string, currency: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SecuritySettings = { two_factor_enabled: boolean, session_timeout: number, password_min_length: number, password_require_special_chars: boolean, password_require_numbers: boolean, login_attempts_max: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NotificationSettings = { push_notifications: boolean, email_notifications: boolean, sms_notifications: boolean, task_assignments: boolean, task_completions: boolean, system_alerts: boolean, daily_digest: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppearanceSettings = { dark_mode: boolean, primary_color: string, font_size: string, compact_view: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DataManagementSettings = { auto_backup: boolean, backup_frequency: string, retention_days: number, export_format: string, compression_enabled: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DatabaseSettings = { connection_status: string, last_backup: string | null, database_size: string, connection_pool_size: number, query_timeout: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type IntegrationSettings = { api_enabled: boolean, webhook_url: string | null, external_services: Array<string>, sync_interval: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerformanceSettings = { cache_enabled: boolean, cache_size: number, max_concurrent_tasks: number, memory_limit: number, cpu_limit: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BackupSettings = { auto_backup: boolean, backup_location: string, encryption_enabled: boolean, compression_level: number, include_attachments: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DiagnosticSettings = { logging_level: string, performance_monitoring: boolean, error_reporting: boolean, health_checks_enabled: boolean, metrics_collection: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SystemConfiguration = { database: DatabaseSettings, integrations: IntegrationSettings, performance: PerformanceSettings, backup: BackupSettings, diagnostics: DiagnosticSettings, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageSettings = { photo_storage_type: string, local_storage_path: string | null, cloud_provider: string | null, cloud_bucket: string | null, cloud_region: string | null, cloud_access_key: string | null, cloud_secret_key: string | null, auto_sync_photos: boolean, sync_on_wifi_only: boolean, max_photo_size_mb: number, compression_quality: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfileSettings = { full_name: string, email: string, phone: string | null, avatar_url: string | null, notes: string | null, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPreferences = { email_notifications: boolean, push_notifications: boolean, task_assignments: boolean, task_updates: boolean, system_alerts: boolean, weekly_reports: boolean, theme: string, language: string, date_format: string, time_format: string, high_contrast: boolean, large_text: boolean, reduce_motion: boolean, screen_reader: boolean, auto_refresh: boolean, refresh_interval: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSecuritySettings = { two_factor_enabled: boolean, session_timeout: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPerformanceSettings = { cache_enabled: boolean, cache_size: number, offline_mode: boolean, sync_on_startup: boolean, background_sync: boolean, image_compression: boolean, preload_data: boolean, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserAccessibilitySettings = { high_contrast: boolean, large_text: boolean, reduce_motion: boolean, screen_reader: boolean, focus_indicators: boolean, keyboard_navigation: boolean, text_to_speech: boolean, speech_rate: number, font_size: number, color_blind_mode: string, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserNotificationSettings = { email_enabled: boolean, push_enabled: boolean, in_app_enabled: boolean, task_assigned: boolean, task_updated: boolean, task_completed: boolean, task_overdue: boolean, system_alerts: boolean, maintenance: boolean, security_alerts: boolean, quiet_hours_enabled: boolean, quiet_hours_start: string, quiet_hours_end: string, digest_frequency: string, batch_notifications: boolean, sound_enabled: boolean, sound_volume: number, };

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSettings = { profile: UserProfileSettings, preferences: UserPreferences, security: UserSecuritySettings, performance: UserPerformanceSettings, accessibility: UserAccessibilitySettings, notifications: UserNotificationSettings, };

