// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StorageSettings = { max_file_size_mb: number, allowed_extensions: Array<string>, temp_directory: string, cleanup_interval_hours: number, enable_compression: boolean, compression_threshold_mb: number, };