export type {
  MaterialType,
  UnitOfMeasure,
  InventoryTransactionType,
  Material,
  MaterialConsumption,
  MaterialStats,
  InventoryStats,
  InventoryTransaction,
  Supplier,
  MaterialCategory,
  InterventionMaterialSummary,
  MaterialConsumptionSummary,
  InventoryMovementSummary,
} from '@/lib/inventory';
